### ISSUE TITLE
French translations borked since commit 9e019ed7e982480a9385d5dbaf813320a84adacb

### ISSUE THREAD

**Issue by Erlotinib** [BestImageViewer/geeqie#1031]
* Bug Report

### GEEQIE VERSION
2.0+

### OS / DISTRIBUTION
Mageia linux 8 x86_64 and Mageia linux Cauldron (development version) x86_64

### SUMMARY

Since commit 9e019ed7e982480a9385d5dbaf813320a84adacb (Fix gettext use with Meson), french translations are not correctly displayed: UI is displayed with a mix of english and french.

(see screenshot: http://mjules.free.fr/captures/Capture%20d%E2%80%99%C3%A9cran_2022-09-04_19-21-00.png )

geeqie is compiled straight from source.

let me know if you need further informations
regard
jules

**Comment by xsdg** [comment]
One thing I notice in that commit is that `po/POTFILES.in` was deleted:
https://github.com/BestImageViewer/geeqie/commit/9e019ed7e982480a9385d5dbaf813320a84adacb#diff-fff7ef1acce73c6891e49f3a0f9a27fe31f6218afdd033ae25e39a6a6d028857

I don't understand our translation infrastructure, but I note that the update to regen_potfiles.sh would imply that `POTFILES.in` should have been renamed rather than deleted:
https://github.com/BestImageViewer/geeqie/commit/9e019ed7e982480a9385d5dbaf813320a84adacb#diff-67528126f91ee8334c5b1d0831d8bf370da443efb92e0862e578a76412bb1dc5

That said, again, I don't understand our translation infrastructure

**Comment by Erlotinib** [comment]
Thanks, it works fine with this patch

regards
jules
