### ISSUE TITLE
Feature request: appImage for aarch64 (arm64)

### ISSUE THREAD

**Issue by kha84** [BestImageViewer/geeqie#1035]
It would be nice to have appImage with the latest version of Geequie not only for x86_64 but also for aarch64, given the growth of ARM SBCs.

**Comment by caclark** [comment]
Linuxdeploy is used to create the Geeqie AppImages, but there is no ARM Linuxdeploy AppImage available at the moment.

**Comment by caclark** [comment]
There is now a preliminary arm64 AppImage. It was created on a Raspberry Pi 4 running Ubuntu 22.04. Perhaps someone could try on something else.

(Upload to GitHub is not possible because of file size)
`
wget https://cclark.uk/Geeqie/Geeqie-aarch64.AppImage
`
It is incomplete at the moment - help, man, and maybe other things, are missing.

**Comment by kha84** [comment]
Big thumbs up

**Comment by caclark** [comment]
AppImages for arm64 are on the download section at geeqie.org.
Commit 42dde6f6

**Comment by kha84** [comment]
Thanks a lot. Many arm sbc users are grateful to you
