### ISSUE TITLE
allow split view with user specified layout

### ISSUE THREAD

**Issue by gbuntu127** [BestImageViewer/geeqie#1077]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION
```
Geeqie 2.0.1 GTK3
```

### OS / DISTRIBUTION
```
NAME="Linux Mint"
VERSION="19.2 (Tina)"
```

### SUMMARY
The current version supports split views of single, horizontal double, vertical double, and quad views. I found it common that I need to compare images in multiple (>2) folders. For example, to split view 3 folders, the quad view will make the view panels too small, it would work better if I could split it into 1 row with 3 columns. Therefore, I am checking if a new feature can be added to allow users to specify the split panel layout by the number of rows and columns. Thanks for the great tool!

**Comment by gbuntu127** [comment]
Thank you for adding the `split triple` feature so quickly, it works perfectly!

**Comment by gbuntu127** [comment]
One minor bug with this solution is: the 3 split pane sizes are not the same (2 of them are the same, while the 3rd one is larger) after hiding the file list pane. It would be nice to fix it if possible, thanks a lot!

**Comment by caclark** [comment]
An immediate work-around is to hide the file list pane first and then select triple, or cycle through another setting - e.g. single, then triple.
You can allocate a keystroke to the split options. Help/Keyboard Map can help you select a spare keystroke.

(The problem is that the computation is done when the option is selected, but not when anything else is changes).

**Comment by gbuntu127** [comment]
Thanks for the workaround.
