### ISSUE TITLE
Cannot build with meson 0.56.2

### ISSUE THREAD

**Issue by gusnan** [BestImageViewer/geeqie#1080]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
Latest Git
```

```
GTK3
```

### OS / DISTRIBUTION

Debian stable

### SUMMARY

Trying to build latest Git on Debian stable (11) with meson 0.56.2 gives
```
meson.build:538:0: ERROR: Function does not take positional arguments.
```

and trying on Debian testing (12) it works (meson 1.0.1), but gives the following warnings:

```
WARNING: Project specifies a minimum meson_version '>=0.53.0' but uses features which were added in newer versions:
 * 0.55.0: {'Passing executable/found program object to script parameter of add_dist_script'}
 * 0.58.0: {'Positional argument to dependency.get_variable()'}
NOTICE: Future-deprecated features used:
 * 0.56.0: {'meson.source_root'}
 * 0.60.0: {'install_subdir with empty directory'}
```

it seems that the set required meson version and the features used doesn't match up. (Positional arguments require 0.58.0)

log on meson 0.56.3:
[meson-log.txt](https://github.com/BestImageViewer/geeqie/files/11373586/meson-log.txt)

log on meson 1.0.1:
[meson-log.txt](https://github.com/BestImageViewer/geeqie/files/11373597/meson-log.txt)

I'm not sure what is the best solution though, Debian 12 will be stable already in June, it might not be a massive problem to not support a that old version of meson).

**Comment by caclark** [comment]
If Debian stable uses 0.56.2, the required version in meson.build can be updated to that - which eliminates the "Passing executable/found" warning.

The problem at around line 540 is only a message to the installer about webp not being installed. This warning can be avoided by putting an "if meson.version() >= 0.xy ... " around those lines.

Shall I make those changes?

[The originating problem might go away anyway - it is because the webp pixbuf loader is not automatically installed along with the other file types - I don't know why.]

**Comment by gusnan** [comment]
> The problem at around line 540 is only a message to the installer about webp not being installed. This warning can be avoided by putting an "if meson.version() >= 0.xy ... " around those lines.

That sounds good to me - I don't mind warnings if it makes it easier when using later versions, but errors are a different thing.
