### ISSUE TITLE
Do you plan to embed video player like gthumb or pix has their own built-in player?

### ISSUE THREAD

**Issue by Stalinist1** [BestImageViewer/geeqie#1185]
Do you plan to embed video player like gthumb or pix has their own built-in player?

**Comment by caclark** [comment]
You can run a video player on a file being displayed by Geeqie, but it requires the user to take extra steps in set it up.

Go to `Edit/preferences/File Filters`, click on the table and then type characters to find the file extension you wish to use. Make sure it is enabled. If an extension does not exist, you must create a new entry.

Go to `Edit/Configure Plugins`. Click `New`. On the `Exec` line use, for example, `vlc %f`. Set a new `Name` and change the desktop file name.

Go to `Edit/Preferences/Behavior` and scroll down to `Play video by left click on image` and select it. Use the `Play with` drop-down to select the plugin you have just created.

You may now click on an image (in the main pane, not a thumbnail) to run a video player.

This takes some effort, but gives flexibility in the choice of video player for example.
Maybe the initialisation process could look for video players and set up the tedious details if one is found.

-----
NOTE
Some recent AppImages do not have the new plugin template. This is fixed in the -latest- AppImages.

**Comment by Stalinist1** [comment]
So complicated!
