### ISSUE TITLE
JXL file is not in the file list

### ISSUE THREAD

**Issue by qkkk8402** [BestImageViewer/geeqie#1209]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
$ geeqie --version
Geeqie 2.0.1 GTK3
```

```

```

### OS / DISTRIBUTION

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

### SUMMARY

While I can open a JXL (JPEG XL) file, I cannot find a JXL file in the left file list.

### STEPS TO REPRODUCE

Open a JXL file, or open one of other format files whose directory has JXL files.

**Comment by caclark** [comment]
Go to `edit/preferences/File Filters`
Click anywhere in the `File Types` list and type `jxl`. If the file type is registered, focus will move to that line.
If it is not enabled, just click to enable it (I do not recall if a restart of Geeqie is required).
If there is no entry for `jxl`, you will need to create one.

Otherwise, at the moment I have no idea...

**Comment by qkkk8402** [comment]
Got it. Sorry, thanks!
