### ISSUE TITLE
Installation with `--prefix=$HOME/.local` requires the access to system directories

### ISSUE THREAD

**Issue by przepompownia** [BestImageViewer/geeqie#1220]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
214be330725538069f3cd5072750cd10e54b4131
```

```
Run-time dependency gtk+-3.0 found: YES 3.24.38
```

### OS / DISTRIBUTION

Debian Sid
### SUMMARY

With the current master version I cannot complete installation because `scripts/update-pixbuf-loaders-cache.sh` attempts to access some system directory (using sudo). 
### STEPS TO REPRODUCE

For me it was 
```sh
meson setup --wipe --prefix=$HOME/.local build/
ninja -C build install
```
Is it possible to respect the prefix instead of accessing system directories?

**Comment by eli-schwartz** [comment]
> With the current master version I cannot complete installation because `scripts/update-pixbuf-loaders-cache.sh` attempts to access some system directory (using sudo).

This seems strange since a meson.add_install_script() is run with the same permissions as the install itself. So if `sudo meson install` installed something to /usr then the install script is already root and doesn't need to use sudo again.

Aside for that, yes, install scripts should operate on the prefix (and more often than not, skip running when a DESTDIR is set).

**Comment by przepompownia** [comment]
Confirmed, thanks!
