### ISSUE TITLE
Renaming files results in a crash

### ISSUE THREAD

**Issue by ZmjbS** [BestImageViewer/geeqie#1242]
**Setup (please complete the following information):**
 - Distribution: Arch
 - Distribution release: Updated two days ago
 - Geeqie version [geeqie --version]: Geeqie 2.2 GTK3

**Describe the bug**
Renaming files using left-click > Rename and either removing characters or adding more than one character to the filename results in a crash.

**To reproduce**
1. create testfilename.png:
touch testfilename.png

2. Start geeqie from the command line.
geeqie &

3. Rename a file to filenam.png (notice the deleted 'e') or filenamexy.png:
Left-click > Rename > edit the textfield and hit enter.

**Expected behavior**
The filename should be renamed. This works if the file is renamed to filenamex.png, though with error messages.

**Error logs or seg. fault files**
Single text file attached with two sets of error messages (one for non-crash, the other for crash). These are short.
[geeqie_bug-rename_x_and_xy.log](https://github.com/BestImageViewer/geeqie/files/14192672/geeqie_bug-rename_x_and_xy.log)

**Comment by tomaszg7** [comment]
I've also seen this crash on my end. It doesn't happen all the time but quite often. In my case it happens after I try to close "rename" window. I run it on Gentoo with Sway/Wayland session both with Wayland native backend and xwayland. Note it happened for me only when I use rename option on clicking the thumbnail.

```
Thread 1 "geeqie" received signal SIGSEGV, Segmentation fault.
0x00007ffff7963965 in ?? () from /usr/lib64/libgtk-3.so.0
(gdb) bt
#0  0x00007ffff7963965 in  () at /usr/lib64/libgtk-3.so.0
#1  0x00007ffff796acf0 in  () at /usr/lib64/libgtk-3.so.0
#2  0x00007ffff7289881 in g_object_unref () at /usr/lib64/libgobject-2.0.so.0
#3  0x00007ffff77fcce9 in  () at /usr/lib64/libgtk-3.so.0
#4  0x00007ffff77fe806 in gtk_main_do_event () at /usr/lib64/libgtk-3.so.0
#5  0x00007ffff7edd515 in  () at /usr/lib64/libgdk-3.so.0
#6  0x00007ffff7f2b2f2 in  () at /usr/lib64/libgdk-3.so.0
#7  0x00007ffff717ed22 in  () at /usr/lib64/libglib-2.0.so.0
#8  0x00007ffff7181ed7 in  () at /usr/lib64/libglib-2.0.so.0
#9  0x00007ffff71827bf in g_main_loop_run () at /usr/lib64/libglib-2.0.so.0
#10 0x00007ffff77fd9ed in gtk_main () at /usr/lib64/libgtk-3.so.0
#11 0x00005555555c7980 in main ()
```

These runtime warnings are non-critical (i.e. not crashes):
```
(geeqie:6477): GLib-GObject-CRITICAL **: 12:05:40.543: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed

(geeqie:6477): GLib-GObject-CRITICAL **: 12:05:40.543: instance with invalid (NULL) class pointer

(geeqie:6477): GLib-GObject-CRITICAL **: 12:05:40.543: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(geeqie:6477): GLib-GObject-CRITICAL **: 12:05:40.543: instance with invalid (NULL) class pointer

(geeqie:6477): GLib-GObject-CRITICAL **: 12:05:40.543: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(geeqie:6477): GLib-GObject-CRITICAL **: 12:05:40.543: g_object_unref: assertion 'old_ref > 0' failed
```

BTW. Two separate issues with rename: 
1. There are two rename dialogs - it depends whether you click the image or the thumbnail. The image one is more functional, while thumbnail one is very basic.
2. The rename windows (and many others...) behave very bad under Sway (and probably other tiling WMs) - they are treated as a "window" and get scaled up to fill in a place in a "tile" instead of appearing as a floating window. Probably some WM hint is missing.
