### ISSUE TITLE
switching between images causes window to keep shrinking

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#133]
I have the "Fit window to image when tools are hidden/floating" option enabled, and the tools are currently hidden.  When alternating between two images, the geeqie window shrinks ever smaller each time the image is changed, until the window is eventually as small as my window manager will allow.  Pressing Z to disable "zoom to fit" mode restores the correct size, but pressing X and switching between images causes the problem again.

Reported by: forest

**Comment by caclark** [comment]
Temporary fix in commit 67d93b5d6 at geeqie.org.
This is obviously a problem with resize-image-to-window/resize-window-to-image somewhere being the wrong way round.
I took a wild guess, made an edit and it seems to work. But this isn't a bug fix, it's just an uneducated guess. There are so many options and other things involved I don't have the inclination to work through it to find if this is really correct.
As far as I have tested, there are no adverse side effects. If someone finds a problem I'll just revert the commit.
There are two very minor problems:
Sometimes the first image displayed is the wrong size - press Refresh
The height parameter is a bit off, perhaps because the size of the window title bar isn't taken into account. In Preferences/Windows set "Limit size when auto-sizing window" to 95% or less.
