### ISSUE TITLE
Geequie randomly forgets option settings

### ISSUE THREAD

**Issue by mkalinski** [BestImageViewer/geeqie#1359]
**Setup (please complete the following information):**
 - Distribution: Fedora
 - Distribution release: 40
 - Geeqie version [geeqie --version]: 2.2 (distro repos) and 2.4 (Flatpak)

**Describe the bug**
When Geeqie is opened, it seems that there's a chance it'll revert any and all options set in `geeqierc.xml` to default values.

I've seen a few bugs open here about certain options being forgotten; to me it seems that all options are subject to this, based on my attempts to configure Geeqie 2.2 and 2.4. This problem did not occur in 2.1.

From my observations, the options are correctly written to `geeqierc.xml` when the preferences dialog is closed, but can be forgotten when Geeqie is opened next time. They can be forgotten all at once, some of them, or none of them. It seems truly random from an user's point of view.

There's nothing in the logs.

**To reproduce**
1. Open geeqie (with default `geeqierc.xml` for better visibility).
2. Change some option(s) (something visible for ease, ex. thumbnail size).
3. Open and close Geeqie; sometimes many times are necessary to trigger the bug.
4. Eventually, the option(s) will be reverted to their defaults after some Geeqie launch.

**Expected behavior**
Geeqie should always remember options set by the user.

**Comment by caclark** [comment]
If the failure occurs during reading the geeqierc.xml file, and you become aware of the failure as Geeqie loads, perhaps at that time you could open a terminal window and save a copy of the configuration file:
`cp $HOME/.config/geeqie/geeqierc.xml /tmp`

Then kill Geeqie so that the config. file is not overwritten and repeat. If the problem is repeatable that is a step forward..

Would you then please upload the file.
