### ISSUE TITLE
Darktable XMP Sidecar Files not grouped

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#147]
Darktable generates .xmp sidecar files w/ the filename pattern FILE.CR2-&gt;FILE.CR2.xmp . Geeqie appears to not recognize this, and appears to accept only FILE.CR2-&gt;FILE.xmp . Adding CR2.xmp to the sidecar extension list does not appear to work. 

Reported by: jhnphm

**Comment by sstent** [comment]
Is there any update on this? It would be very helpful!

**Comment by paperdigits** [comment]
Hi, is there any update on this issue? I'd really like to be able to choose whether it is filename.xmp or filename.ext.xmp.

Thanks!

**Comment by paperdigits** [comment]
Would any of the Geeqie developers be willing to start a bounty for this?

**Comment by caclark** [comment]
This is the origin of the first message:
https://sourceforge.net/p/geeqie/bugs/147/
I do not know if the patch referred to was implemented, because over the years the code has changed so much.
But if you set up a new filter (Edit/preferences/files/file types) containing for example, 
File type: .jpg.xmp 
Class: Metadata
.. and then you probably need a re-start to regenerate the filter list.
You should then see filename.jpg and  filename.jpg.xmp listed in groups.

However then things go wrong. If you use Geeqie to copy or move a grouped file, you will get warnings. If you push past that, you will find that the sidecars have been renamed!
If you disable file grouping and then copy or move, warnings are still issued but the file names are unchanged.
It's a bit messy.

**Comment by tomaszg7** [comment]
I can't get .cr2.xmp files to group with .cr2 files. Regardless if I have .xmp or .cr2.xmp in File types (or both) they are listed separately.

Moreover, there is an issue of writing metadata. Geeqie does that via exiv2 and from I could gather it is not easy to change naming scheme. As effect I had to write my metadata directly to cr2 files to get reasonable interoperability between various programs.

**Comment by caclark** [comment]
The grouping with cr2 files works on my system. Could you check that you have something like:
%image;%raw;%meta
in the Grouping Sidecar Extensions box?

**Comment by tomaszg7** [comment]
Ah, sorry, I didn't notice that box. It contained ".jpg;%raw;.ufraw;.xmp". I updated it and now it works as expected.

**Comment by caclark** [comment]
If the problem you have is Darktable writes to filename.ext.xmp and Geeqie wants to write to filename.xmp, is this just a problem of one file needing two names -  i.e. could be at least be reduced with symbolic links?
Could you run inotify on your working directories to create symbolic links?
There would still be problems with asynchronism, and copying/moving symlinks.

**Comment by tomaszg7** [comment]
I think I could do it. It's kinda messy but should work. At the moment I'm comfortable with my solution (writing metadata into .cr2 files), but I'll keep it in mind when I'll revisit the problem.

**Comment by paperdigits** [comment]
I am not comfortable writing metadata into raw files, as my raw files are made read-only after import. I don't really like the symlink idea, though it is probably workable, but I don't want to litter my photo directory with more symlinks (I'm using git-annex which already uses symlinks).

**Comment by tomaszg7** [comment]
Got bored today and took another shot at the problem. I had more luck this time (it had to be luck since I don't know geeqie code at all) and managed to at least partially solve it. With this patch geeqie writes sidecars in the format "image.ext.xmp" but still reads and modifies also "image.xmp" files. However user needs to add all possible combinations of ".ext.xmp" to the file filter manually.

I don't know if it is the right approach, but I'll try to polish it a bit, add config options and so on.

[geegie-sidecar.patch.gz](https://github.com/BestImageViewer/geeqie/files/786457/geegie-sidecar.patch.gz)

**Comment by tomaszg7** [comment]
I updated the patch a bit  - added an option in Edit/preferences/metadata controlling the name of the created sidecar files. 

I still can't find a way to make default filter sidecar entry to work for the new scheme as well. It is probably a simple modification provided that one knows where it should be made ;)

[geeqie-sidecar.2.patch.gz](https://github.com/BestImageViewer/geeqie/files/791870/geeqie-sidecar.2.patch.gz)

**Comment by paperdigits** [comment]
That's awesome @tomaszg7 !

**Comment by caclark** [comment]
Could you use registered_extension_from_path() in filefilter.c to get the extended extension? If the extension_list is sorted so that the double-extensions are at the top of the list, maybe?

**Comment by caclark** [comment]
"However user needs to add all possible combinations of ".ext.xmp" to the file filter manually."

I'm not sure that would be necessary. The routine filter_add_defaults() in filefilter.c is where the list is set up - just add to the list in the code all the combinations you think most users will need.

**Comment by tomaszg7** [comment]
> Could you use registered_extension_from_path() in filefilter.c to get the extended extension? If the extension_list is sorted so that the double-extensions are at the top of the list, maybe?

You mean that I could do it instead of changing file_data_get_sidecar_path? Seems that making sure that extension_list is always properly sorted would be more complicated than what I did.

> I'm not sure that would be necessary. The routine filter_add_defaults() in filefilter.c is where the list is set up - just add to the list in the code all the combinations you think most users will need.

True, but it creates a mess. One single entry for .xmp should be able to take care of all those things. Also depending on user to remember to add corresponding extended extensions for new file types he defines is a risky thing.

**Comment by tomaszg7** [comment]
I created a branch in my fork and pushed a commit there: https://github.com/tomaszg7/geeqie/tree/sidecar_extensions

**Comment by tomaszg7** [comment]
I added some changes and now it should work without extra entries in file filter. Not sure if there are no bugs lurking somewhere. I don't think that it should go with another preferences switch.

This works by changing the functions responsible for grouping (i.e. creating basename_hash). After doing that I also got the idea that @caclark suggestion of using filter_add_defaults() might be modified/expanded to automatically add ".ext.xmp" entries for all listed extensions of image and raw class. I'm not sure which would be better.

BTW. If there are several sidecar files (and possibly some metadata in the image itself) Geeqie in most cases reads only one of those (on purpose). Eg. if I have keywords in .cr2 files and sidecar .cr2.xmp files from darktable without keywords, Geeqie shows only what can be found in .cr2.xmp. The rationale found in source code is such that the presence of sidecar file suggest that the image file might not be writeable, thus it might not be possible to remove keywords from there.

**Comment by caclark** [comment]
With this implementation, an extension of .jpg.xmp is shown in the grouped files as just .xmp. Maybe this will be confusing to some users. Also it looks to me that if you copy a grouped file, the extension of .jpg.xmp gets renamed to just .xmp without any warning.

Commit 58e4671ba was specifically to allow dots in extension names (probably just to allow .cr2.xmp etc.). The problem that created was during a copy/move, there was a warning that the extension of the destination was different. But if the operation was carried out the file extension was changed. 

If lines 2098 and 2375 of filedata.c are changed from extension_from_path() to registered_extension_from_path(), and the extended extension is registered in the filter list, these problems are solved.

Maybe that modification should go into the repository if no other solution can be found.

**Comment by tomaszg7** [comment]
I don't think that extension shown on top of the group is a problem. I think it should rather describe what types of objects are in the group, not exactly how they are named. 

All the problems with renaming/moving/copying slipped my mind. It seems that current version is also a mess and probably all uses of extensions in geeqie should be reviewed. For example remove_extension_from_path() might be inconsistent with both  extension_from_path() and registered_extension_from_path(). Thus e.g. unique_filename_simple() might create weird results.  It seems that "foo.bar.bar.jpg" would get unique filename as "foo_.jpg". And it might moreover depend on file filter entries. 

I'll try to see what can be done, but maybe commit https://github.com/BestImageViewer/geeqie/commit/58e4671ba18ae3b3a996f3f518151fc6fb2bbdf0 should be partially reverted. I.e. I don't think Geeqie really need two different functions for extensions. I think that "foo.bar.bar.jpg" should be split into extension ".jpg" and basename "foo.bar.bar" (unless some weird file filter entry is present) and both of them could be stored as fields in FileData. It seems it would make copy/move operations easier.

BTW. Maybe copy/move dialog should have a switch to disable moving sidecar files together. In the usual sense when sidecar = xmp, it usually makes no sense to leave them, but sidecar in Geeqie mean any elements of group other than parent file. It could be a jpg file accompanying a cr2 file (or the other way around). 

BTW2. sidecar_priority should also be probably refined a bit, so that e.g raw files have higher priority than image files.

**Comment by tomaszg7** [comment]
Ok, did that in my branch. Seems to work in my case (grouping, moving and so on). However I can't guarantee it is bug-free, but it should work regardless if extended extensions are listed in file filter.

**Comment by caclark** [comment]
"BTW2. sidecar_priority should also be probably refined a bit, so that e.g raw files have higher priority than image files."
Do you mean that when files are grouped, the raw file name should be the filename displayed, and the others listed as the sidecars? If so, this can be changed by the order of the parameters in "Grouped sidecar extensions" e.g. %raw;%image;%meta.

I think there is a bit of a problem with Rename - in the released version, all files in the group are renamed (which I think is the correct action). But in the version in your branch this does not happen.

[And in whichever version, Delete does not work as I expect. With grouped files the message "This will delete the following files" is given - but only the first file in the list is deleted. But that's another problem.]

**Comment by tomaszg7** [comment]
> Do you mean that when files are grouped, the raw file name should be the filename displayed, and the others listed as the sidecars? If so, this can be changed by the order of the parameters in "Grouped sidecar extensions" e.g. %raw;%image;%meta.

Yes, that's what I meant. I didn't notice that it works that way. Thanks. The sorting function put me on the wrong trail.

As to the rename/delete problem I think I solved it in the last commit - however at the price of adding an extra field into FileData struct. It seems to work now in all test cases I could think of, but as I rarely use some of the features, I may have broken something else... 

Thank you for checking my code, I seem to be breaking more than I fix. That's probably to be expected given my very poor knowledge of Geeqie codebase.

**Comment by w-oertl** [comment]
I've noticed this issue too, and wrote a small shell script to rename .xmp files to .nef.xmp after geeqie has messed things up. Thumbs up for this patch!

**Comment by caclark** [comment]
I don't understand how the code works, but so far as I can see this works as intended. [Delete group doesn't work, but no-one has complained about that, so I don't think it is important].
Maybe this should go into the repository?

**Comment by tomaszg7** [comment]
> [Delete group doesn't work, but no-one has complained about that, so I don't think it is important].
Really? Do you delete it in some special way? When I use "del" key or "Delete" from the context menu it works just fine (in all cases I could think of: img.jpg + img.xmp, img.jpg + img.jpg.xmp, img.jpg + img.xmp + img.jpg.xmp).

If you think the code is OK, I can create a pull request.

**Comment by caclark** [comment]
I'm sorry, but I am sure this is not functioning on my system. Could you make sure the sidecars are really deleted by using an old-fashioned command line operation (maybe you have some filtering set up that hides the sidecars).
If that doesn't provide an answer, perhaps you could let me have details of your system set-up; I will try to replicate that as far as I can and do some more tests.

**Comment by tomaszg7** [comment]
That's very suspicious. Did you pull last commits? (Specifically https://github.com/tomaszg7/geeqie/commit/9da14a980e11a3cc957fb46795220afecb870782). Of course I verify that sidecars are gone via command line.

I don't know what possible details of my system might be relevant. I'm using 64-bit Gentoo with kernel 3.9. Geeqie is build with GTK3 and --enable-developer. Here's my example test case:

touch img.jpg
touch img.jpg.xmp
[delete in geeqie]
ls

**Comment by caclark** [comment]
Sorry, this was my stupid mistake. I have a geeqie-delete-command.desktop set up to use gvfs-trash. But I had used the %f (single file) instead of %F (multiple file) option.
I will put a commit into the geeqie.org repository sometime soon.

**Comment by caclark** [comment]
Fixed in commit 2be9b24c7 at geeqie.org

**Comment by tomaszg7** [comment]
Do I need to create pull request here on Github as well, or will that be merged here automatically?

**Comment by caclark** [comment]
The problems of keeping the repositories in sync was discussed in #471.

**Comment by caclark** [comment]
Hello Tomasz
By chance I encountered this problem, which is related to this thread:
1. select GQview legacy on the preferences/metadata tab
2. Choose a file-type that is not writable, and no sidecars
3. Try to write a Comment to metadata

Geeqie seg faults at line 305 in metadata.c, trying to write to /somewhere/filename.ext.meta

strcmp is used (as in many other places) whereas g_strcmp0 is probably safer. And maybe .meta should be a registered file extension - I don't know why it isn't.
I assume no-one uses legacy format any more, so I guess this isn't so important.

**Comment by tomaszg7** [comment]
Sorry for the delay in responding. 

I see the problem and it seems the most reasonable to fix it by adding .meta to the list of registered file extensions. It seems to fix the problem for me https://github.com/tomaszg7/geeqie/commit/30d827bed0358bb928a9a926e109665f2e880d1e

I can't say anything definite about replacing strcmp with g_strcmp0. It would prevent the segfault here,  but the Geeqie behaviour would probably be incorrect. Unsafe strcmp might be viewed as a way to catch unexpected situations ;)

**Comment by tomaszg7** [comment]
I noticed that the fix for the crash didn't land in the tree. Was it simply an omission or do you think some deeper solution is needed? Or maybe even pruning the legacy support code?

**Comment by caclark** [comment]
Commit ac74cef5f4 at geeqie.org.
I simply forgot. Thanks for reminding me.

> pruning the legacy support code

Ideally, yes, but probably not worth the effort.  I'd rather spend time trying to fix things that are broken, than things that are not (yet) broken.  Anyway, breaking something that is already broken is not as embarrassing as breaking something that was once working!

**Comment by tomaszg7** [comment]
Just a heads-up - I noticed another bug in grouping code. If I have the series of files called imgXXXX.cr2 and imgXXXX.cr2.jpg (I know that the name is stupid but was to lazy to polish the script), then Geeqie sometimes groups them, and sometimes not. It depends on the order in which the are processed. I hand-fixed that problem for `file.cr2.xmp` by postponing processing sidecars after other files are read. 

I don't know yet how best to solve it - maybe just by sorting the file list according to name length. I don't like the idea as it would probably slow Geeqie down on big directories even more (I still struggle with the problem - yesterday by opening a directory with thumbnail cache with +40k files I managed to destabilize Geeqie: hang debugging thread, weird clicking reactions, ...). Now I start to wonder if the slowdowns I experience are related to the code for grouping. It requires a lot of hash lookups which might become expensive. I'll have to check.

**Comment by tomaszg7** [comment]
I don't have a lot time now to dig through the code in the next weeks. It looks like I inadvertently the behaviour of the function and your solution seems valid. The function should return empty string (ie. pointer to NULL), not a null pointer. 

However it seems without digging that there is another bug elsewhere, as even with your change, that function might still return `NULL` if `path = NULL`. We should probably review all calls to `remove_level_from_path()` and check if it is protected at all places from NULL value. Or maybe path can't ever be NULL, which would make the check superfluous (to be replaced by `g_assert()`?).

**Comment by caclark** [comment]
Fixed in commit 5fc1f749 at geeqie.org
