### ISSUE TITLE
Latest AppImage fails to run

### ISSUE THREAD

**Issue by jefferysmall** [BestImageViewer/geeqie#1534]
**Setup (please complete the following information):**
Xubuntu 24.04.1
 Geeqie-latest-x86_64.AppImage apparently compiles on 10-30-24

**Describe the bug**
I've been using the extracted AppImage from 09-02-24 for a while with only the previously reported problems, along with many previous AppImage versions.  On 10-31-24 I just downloaded the current AppImage (187MB) listed as built 'yesterday' so 10-30-24.   I extracted it and attempted to run it (Geeqie_241030/AppRun) and it says:

**APPRUN_ERROR: No such file or directory**  (Note, no <CR> after this message.)

I've run it as

**Geeqie_241030/AppRun**

as well  as

**Geeqie_241030/AppRun --geometry=1852x2039+989+41 --disable-clutter  .**

So specifying a starting directory (.) is not the problem.

Also, when starting geeqie, all recent versions spit out the message: 

**Gtk-Message: 16:03:56.910: Failed to load module "xapp-gtk3-module"**

libxapp-gtk3-module  2.8.2 is installed on this machine, but as this is an AppImage that shouldn't matter.  It should have the module as part of the packaging and I find nothing applicable in the extracted directory.

**Comment by caclark** [comment]
This is a bug, probably as a result of upgrading GitHub runners to Ubuntu 24.04.

If you used `geeqie-download-appimage.sh`, you can retrieve a backup:
`geeqie-download-appimage.sh --help`

**Comment by Johnreidsilver** [comment]
first time user here also getting
./Geeqie-minimal-latest-x86_64.AppImage 
APPRUN_ERROR: No such file or directory

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy

**Comment by caclark** [comment]
Something has gone wrong in the software used to create the AppImages - but I do not see where.
I think I will have to change the way the images are created - that may take some time.
In the meantime, these are the last-good versions:
`wget https://cclark.uk/geeqie/appimages/Geeqie-latest-x86_64.AppImage `
`wget https://cclark.uk/geeqie/appimages/Geeqie-minimal-latest-x86_64.AppImage`
`wget https://cclark.uk/geeqie/appimages/Geeqie-latest-aarch64.AppImage`
`wget https://cclark.uk/geeqie/appimages/Geeqie-minimal-latest-aarch64.AppImage`

**Comment by richardstevenhack** [comment]
Same issue on latest openSUSE Tumbleweed AppImage.

**Comment by richardstevenhack** [comment]
Where did my comment go?

I just tried the known good AppImage and it won't run.

There is an official release for openSUSE Tumbleweed but it is version 2.4. I will try to run that version until a fix is available for the AppImage which won't run on Tumbleweed.

**Comment by caclark** [comment]
> I just tried the known good AppImage and it won't run.

Is the error message also `APPRUN_ERROR: No such file or directory`  ?

**Comment by richardstevenhack** [comment]
Well, this has just become a nightmare.

Here is what I'm trying to do.

I run AppImages using AppImageLauncher. I set the permissions on the AppImage to make it executable. I then click on the AppImage which causes Dolphin's "Execute" dialog to pop up. I click on "Execute" and AppImageLauncher takes over and "integrates and runs" the AppImage. This means it puts the AppImage in the KDE Menu and a KDE desktop file and runs the app.

The proper way to install an AppImage in Linux is to download the AppImage and let the user place it where he wants and execute it the way he wants using a utility or not as he wants.

Now when I use your script to download the AppImage to the /home/bin directory. I used the extract option because I wanted to run the AppImage from my Linux Programs directory using AppImageLauncher.

This does not work.

So then I removed the previous AppImage, and used the script to download and extract again. Your script set the symbolic link, and I then executed the geeqie command from the command line. I get this result:

`rhack@localhost:/Data2/Work> geeqie
Gtk-Message: 12:33:02.866: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:33:02.883: Failed to load module "colorreload-gtk-module"
Gtk-Message: 12:33:02.883: Failed to load module "window-decorations-gtk-module"
sh: /home/rhack/bin/Geeqie-latest-x86_64-AppImage/squashfs-root/usr/lib/x86_64-linux-gnu/libreadline.so.8: no version information available (required by sh)
sh: /home/rhack/bin/Geeqie-latest-x86_64-AppImage/squashfs-root/usr/lib/x86_64-linux-gnu/libreadline.so.8: no version information available (required by sh)
sh: /home/rhack/bin/Geeqie-latest-x86_64-AppImage/squashfs-root/usr/lib/x86_64-linux-gnu/libreadline.so.8: no version information available (required by sh)
sh: /home/rhack/bin/Geeqie-latest-x86_64-AppImage/squashfs-root/usr/lib/x86_64-linux-gnu/libreadline.so.8: no version information available (required by sh)
sh: /home/rhack/bin/Geeqie-latest-x86_64-AppImage/squashfs-root/usr/lib/x86_64-linux-gnu/libreadline.so.8: no version information available (required by sh)
sh: /home/rhack/bin/Geeqie-latest-x86_64-AppImage/squashfs-root/usr/lib/x86_64-linux-gnu/libreadline.so.8: no version information available (required by sh)
sh: /home/rhack/bin/Geeqie-latest-x86_64-AppImage/squashfs-root/usr/lib/x86_64-linux-gnu/libreadline.so.8: no version information available (required by sh)
sh: /home/rhack/bin/Geeqie-latest-x86_64-AppImage/squashfs-root/usr/lib/x86_64-linux-gnu/libreadline.so.8: no version information available (required by sh)
sh: /home/rhack/bin/Geeqie-latest-x86_64-AppImage/squashfs-root/usr/lib/x86_64-linux-gnu/libreadline.so.8: no version information available (required by sh)
sh: /home/rhack/bin/Geeqie-latest-x86_64-AppImage/squashfs-root/usr/lib/x86_64-linux-gnu/libreadline.so.8: no version information available (required by sh)
sh: /home/rhack/bin/Geeqie-latest-x86_64-AppImage/squashfs-root/usr/lib/x86_64-linux-gnu/libreadline.so.8: no version information available (required by sh)
sh: /home/rhack/bin/Geeqie-latest-x86_64-AppImage/squashfs-root/usr/lib/x86_64-linux-gnu/libreadline.so.8: no version information available (required by sh)
Stack trace (most recent call last) in thread 796747:
#4    Object "/lib64/libc.so.6", at 0x7fefc831d5fb, in 
#3    Object "/lib64/libc.so.6", at 0x7fefc82983b1, in 
#2    Object "/home/rhack/bin/Geeqie-latest-x86_64-AppImage/squashfs-root/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0", at 0x7fefc97cbc81, in 
#1    Object "/home/rhack/bin/Geeqie-latest-x86_64-AppImage/squashfs-root/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0", at 0x7fefc97d1541, in 
#0    Source "/home/runner/work/geeqie/geeqie/build/../src/utilops.cc:529", in file_util_data_free(UtilityData *ud) [0x55f6db82329c]
Segmentation fault (Address not mapped to object [0x1a])
Segmentation fault (core dumped)
`
Now previously when I ran the AppImage installed using the AppImageLauncher from the KDE Menu, it would start up and immediately fail. I assume it would have had the same errors as above, but I don't know that as I did not run it from the command line.

OK, so now I just took the "Geeqie-latest-x86_64" and moved it to my Linux Programs directory, changed to that from the command line, and executed the AppImage directly from the command line. AppImageLauncher wanted to grab it and integrate, but I told it to "Run Once" instead. I got the same errors above.

OK, so I ran the script again, installed the Geeqie binary with the Geeqie directory under /home/bin. Then I changed over to /home/bin and from the command line ran the Geeqie binary, not the AppImage. I got the same errors.

I am assuming now that your AppImages for some reason do not work with the AppImageLauncher - even though every other ApppImage I have on the system does. Nor does the binary work on Tumbleweed at all.

The only thing that works is the official openSUSE release of the previous version and the Flatpak version which is not developed on the correct platform.

I have just spent two hours on this issue because the Flatpak platform is out of date. The only reason I am using Geeqie instead of Gwenview (which I also have on both systems) is because I want Geeqie to run a recursive slideshow on the monitor on the other system, not my main system. So I'm going to uninstall Geegie from my main system and leave the other system on the openSUSE official release version until such time as you sort all this out.
