### ISSUE TITLE
Cannot symlink file if two geeqie instances are running

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#162]
I noticed that the File → Create symbolic link menu entry does not work
from a second instance of geeqie, started while another is already
running. It seems that geeqie starts a helper which tries to talk to the
running instance and then talks to the wrong one.

Reported by: nijel

**Comment by caclark** [comment]
Fixed in commit 69022467 at geeqie.org.
A second instance cannot be started. Use File/New Window instead.

**Comment by tomaszg7** [comment]
That is really not a solution, it broke more than it fixed. You made Geeqie silently exit without giving a reason when one attempts to start a new instance. For example, when you have Geeqie already running and you click on an image, nothing will happen. That is both confusing and counterproductive. I don't even see a command line option to work around the problem.

I think some kind of solution would be to make Geeqie pop out a new window automatically when one tries to start a new instance. It would be even better if the behaviour would be configurable, e.g. if user could choose if `geeqie image.file` should pop a new window or display image in the existing one. I don't see how anyone would expect Geeqie to silently die in this situation.

**Comment by caclark** [comment]
In the next few days I will make some more commits involving --remote commands and layout window identifiers.
One item included will be a --remote command to open a new window. That will enable a new window to be opened in the initial geeqie instance whenever a second call to geeqie is made.

**Comment by caclark** [comment]
It isn't possible to open a new window in the original instance without using the --remote facility (as far as I can see).
When you execute a --remote command, a second instance is created, but all it does is send the command to the first instance, and then terminates.
So what I intend is to include an call to --remote --new-window in that newly amended section of main - that will cause a new window to be opened without the user having to type anything other than "geeqie".

[Also whenever I open an image file from a file manager with right-click open-with, the image is opened in the existing instance. This is because the .desktop file aliases "geeqie" to "geeqie -r" (ok, it isn't an alias, but it has the same effect)]

**Comment by caclark** [comment]
Commit 01fd562 at geeqie.org contains the changes

**Comment by tomaszg7** [comment]
Now it's much better, however cluttering window title with window ids is not an elegant solution. Only a handful people will probably use the new `--id` command, so it might be a good idea to make it configurable (maybe even disabled by default). Maybe even window title could be configurable in a similar way as overlay. That's something e.g. GIMP does.

**Comment by caclark** [comment]
> configurable in a similar way as overlay. That's something e.g. GIMP does.

There is a "Pimp my Gimp" webpage! Who says programmers have no sense of humour. Maybe there should be a "Geek my Geeqie" page.

Commit fcf4c376 at geeqie.org makes the display of ID selectable. Off by default.

**Comment by tomaszg7** [comment]
Didn't you delete by mistake the line
```options->save_dialog_window_positions = FALSE;``` 
from `options.c`?

**Comment by caclark** [comment]
Thanks.
Committ 379823d7 at geeqie.org
