### ISSUE TITLE
Hyper quality sometimes shows blurry image at 1:1

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#192]
Tiff files created with GIMP 2.8.6 appear blurry in 1:1 view, while png, bmp and jpg work fine. Tiff compression options don't seem to have any effect. GIMP loads fine those tiffs as gwenview does. Tested on Archlinux i686.

Reported by: johnl2005

**Comment by casta** [comment]
Confirmed: when using “Hyper” resizing, images viewed at 100% are blurry (jpeg affected too). Downgrading to Bilinear fixes the issue.
Using the last git revision here.

**Comment by caclark** [comment]
The bug was introduced in the change from commit 808d8558b to 3dd0e08368b.
It's clear the change there affected only rt_tile_render() in renderer-tiles.c.
But things have changed so much since then I am at a loss to understand where the bug is now. Maybe someone else has some ideas.

**Comment by Beep6581** [comment]
The issue topic should be updated.

**Comment by caclark** [comment]
Fixed in commit a920f59f96 at geeqie.org.
Up to commit 808d8558b3d5 alpha-channel files at scale 1:1 always had
GdkInterpType set to GDK_INTERP_NEAREST - the lowest quality. As there
was no scaling at 1:1, this was ok.
The documentation shows that GDK_INTERP_HYPER is "idempotent" at scaling 1:1 - I assume that means the filter can be applied multiple times with the same result. But it seems it does have an effect on the first application.
This commit reverts to the previous method.
