### ISSUE TITLE
Geeqie 1.1 stalls for 10+ seconds when opening a collection

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#204]
I just upgraded to Lubuntu 14.04, which provides Geeqie 1.1, and now, when opening a collection, Geeqie freezes for 10+ seconds before the window appears.

As far as I can tell from strace's output, somewhere between Geeqie 1.0 and 1.1, it started doing a huge enough flood of stat() calls to freeze the UI while it's waiting on the filesystem.

I can't offer you the collection in question, since there's sensitive stuff in the filenames, but it contains 633 images and here are some telling details about the strace output:

ssokolow@monolith ~ % grep stat( statlog.txt | wc -l
1101315
ssokolow@monolith ~ % grep stat( statlog.txt | sort | uniq | wc -l
33660

My best guess is that, somehow, Geeqie 1.1 is statting everything in the parent folders of the images in the collection and doing the exact same stat calls over 30 times each.

(And, remember, this is between picking a collection from the MRU list and having the window appear)

Since responsiveness is the whole reason I use Geeqie, I grabbed the Geeqie 1.0 .debs from the Ubuntu 12.04 repos and opted out of package upgrades.

(Doing so also fixed the other bug I already reported and the crasher I'm about to report as soon as I generate a backtrace on it)

Reported by: ssokolow

**Comment by caclark** [comment]
The current version opens a collection with 1500 images with no problem. I assume the bug has been fixed.

**Comment by tomaszg7** [comment]
I recently "feel" that Geeqie is very slow when opening directories, but I didn't measure it. Seems that I have a second or two delay on opening even when directory has as few as 100 .cr2 files (even without .xmp sidecars, which seem to understandably make it even worse).

**Comment by caclark** [comment]
If I start Geeqie from the command line, pointing it to a folder with 1500 20MB .nef files, it will load itself and the folder in about 1/2 sec.

I would suggest you start Geeqie in as minimal a way as possible (for example, I recently found that when I ran Geeqie from a script that set XDG environment variables, it was very slow - I have not yet bothered to resolve that problem).
But try starting Geeqie in list mode, not icons, and sort order set to name or date.
If the problem still exists, I will try to work out some way to get relevant debug timings to see where the problem is. It really shouldn't be that slow -  unless you are regenerating thumbnails etc. every time.

**Comment by tomaszg7** [comment]
Regenerating thumbnails wouldn't be an issue - they are generated after UI is refreshed.

When I start Geeqie in a directory of 500-5000 jpg files (from command line), it sometimes takes even 10s to show the window (afterwards it is almost immediately responsive). However I remember even longer startups (but it was from some KDE app, so environment might be different). It was in "name" sort mode, thumbnails enabled. Disabling thumbnails doesn't seem to affect the problem. 

At some point I even wanted to make "git bisect" to see when the problem was introduced (it was not very long ago, definitely this year). However as soon as I tried to do it, the problem disappeared for some time :) Didn't figure out what caused it. Now it seems to be present again...
