### ISSUE TITLE
marks do not persist

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#220]
I just went through a large library, marking files by pressing "1", then accidentally exited Geeqie before I could move them and lost all my work.

Now I tried various settings for Metadata saving, but it seems there is no support for saving Marks, so I suppose this is a feature request.

Reported by: unhammer

**Comment by caclark** [comment]
This has been discussed elsewhere. The design is for keywords to persist, but marks are just for temporary use.

**Comment by dozylynx** [comment]
If marks are not intended to persist then it would be less frustrating to make that evident, and preferably obvious, in the user interface so that nobody spends time applying marks only to lose them all.
The current behaviour does not reflect well on the software: it looks broken.

**Comment by caclark** [comment]
A message could be raised before exit warning the user that marks have been set - but that would not help much if the user has a considerable amount of work-in-progress and no time to do anything about it. The only option would be to hibernate the computer instead of a shut-down.

A message could be raised on start-up warning the users of factors such as this. Also not wonderful.
[A message system warning users of new/changed functions with  "ok/do not show again" buttons might be a useful thing whenever new versions of Geeqie are made]

The user could link marks to permanent keywords named Mark 1, Mark 2 etc. Using xmp data for temporary work is a bad idea (and I've had quite a few of those).

Maybe things have changed since 2007 when the Marks feature was first implemented. The number of images people store has probably increased significantly in the same way memory installed has increased. This means that users could be spending a significant time organizing images -  with the result that such work-in-progress may extend over more than one session.
If so, I guess the solution is to store the current marks settings in geeqierc.xml or some other text file. It might not be too difficult to do if error checking/data consistency etc.  is kept to a minimum.

**Comment by caclark** [comment]
The attached .diff file might be a solution.
An option in Preferences/Behaviour permits the marks settings to be preserved. The default is to save.
There is also a menu item to clear all marks from all images.
[save_marks_1.diff.gz](https://github.com/BestImageViewer/geeqie/files/1959131/save_marks_1.diff.gz)

**Comment by caclark** [comment]
Implemented in commit 850bd515 at geeqie.org

**Comment by dozylynx** [comment]
Fantastic work. I've just built from source and tested this and can confirm that marks are correctly preserved across closing the application and restarting it. Thanks!

**Comment by caclark** [comment]
A problem resulting from marks being preserved is that files with marks set can be in any long-forgotten folder - and the user has no way of finding them.
In a few days I will implement another option in the search window to find files with marks.

**Comment by caclark** [comment]
Commit c4d700ed at geeqie.org has an additional search parameter to find files which have marks set.
