### ISSUE TITLE
GIF animation support

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#254]
For many years GIF animations are the only reason that forces me to have another image viewer installed. If adding support for them in geeqie is possible without sacrificing it's speed and bloating it with many new dependencies it will be great.

Reported by: dkavlakov

**Comment by mowgli** [comment]
@richih, @pander, @laley, @haarp, @dkavlakov, hope, you are the same than on SF... If so, please leave a note to keep informed.

I don't see the high priority for this issue but I see some needs for it.

**Comment by PanderMusubi** [comment]
Would it help to set a bounty on this issue via BountySource?

**Comment by RichiH** [comment]
I commit to 20€ for animated GIF, 50€ for GIF and basic webm.

Richard

Sent by mobile; excuse my brevity.

**Comment by Frodox** [comment]
+1 and up

**Comment by SimonDedman** [comment]
Hi guys. I've been scouring this issue and found out that the very excellent Christian Heckendorf has fixed it! At time of discussion (16/10/2016) his patch hadn't been committed into Geeqie main so if you want it you have to do it yourself:
Download/clone his [fork](https://github.com/heckendorfc/geeqie/tree/animation) and compile & install in the standard Geeqie way:
```
./autogen.sh ; make
make install
```
This was a lot of work for me, errors and bugs up the wazoo. If you're in the same boat, `autoreconf` and `sudo apt install gtk-2.0-dev` and `sudo apt install gtk-3-dev` then the autogen commands seemed to work. My install is buggy as hell and animation doesn't seem to work, but... there you go!!

Hopefully Christian's patch can be integrated into the main branch and we'll be set. Cheers all.

**Comment by mowgli** [comment]
Well, some bounties might help. But maybe Christian Heckendorf who has more than a idea how to integrate it. :-)

For me, that would not help; not in this case. ;-)

**Comment by mowgli** [comment]
Closed with 3ad88b1. Credits to Christian.

**Comment by dandv** [comment]
Can we please have a new release with animated GIF support? The [latest release here is 1.3](https://github.com/BestImageViewer/geeqie/releases), from May 2016, and the latest I can get from the Ubuntu repos is 1.2.2.

**Comment by PanderMusubi** [comment]
See https://launchpad.net/ubuntu/+source/geeqie Ubuntu is already at 1.3, but without animated GIF support.

**Comment by Erhannis** [comment]
I just cloned and built the repo, but it still shows gifs as static.  Did it get broken?  Does it still work for anybody else?

**Comment by caclark** [comment]
It is a selectable item which is off by default. It is on the View menu, and the hot-key is A.

[Also, it is not documented]

**Comment by PanderMusubi** [comment]
On Ubuntu with geeqie 1:1.3-1 it is not present. From which version onwards is it expected to work?

**Comment by caclark** [comment]
At the moment it is only available in the repositories at geeqie.org and here at github.

If you need to use the latest version, it takes only a couple of minutes to clone and compile Geeqie from the repos.

**Comment by PanderMusubi** [comment]
Thanks, that works, although GIF animation is not enabled by default. If it could be the default, please make it so as for many users that is too much to ask to search for how to enable it.

Also I got these messages on the command line that might need some attention:

    (geeqie:18297): Gtk-WARNING **: Allocating size to GtkWindow 0x56331ce802c0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

    Error: XMP Toolkit error 203: Duplicate property or field node
Warning: Failed to decode XMP metadata.

    Warning: Directory Image, entry 0x0001 has unknown Exif (TIFF) type 0; setting type size 1.

    Error: Upper boundary of data for directory Sony1, entry 0x9008 is out of bounds: Offset = 0x000008fc, size = 200, exceeds buffer size by 76 Bytes; truncating the entry

**Comment by victort** [comment]
👍 for gif animation. thanks for the work.

**Comment by PanderMusubi** [comment]
For more information on the next release, please see https://github.com/BestImageViewer/geeqie/issues/530

**Comment by PanderMusubi** [comment]
Small question on the default setting, would enabling animation for animated gifs by default be desirable over disabling it by default?

**Comment by RichiH** [comment]
Enable, please.

Richard

Sent by mobile; excuse my brevity and the wall of text Gmail appends by
default.

**Comment by caclark** [comment]
Animation enabled by default in commit 8e848353 at geeqie.org

**Comment by deltaray** [comment]
I'd just like to share some thoughts here and I don't mean to offend anyone here, I just want to try to provide some perspective from a long time user. Over time I've seen some open source projects become out of touch with the interests of their active user community. Likewise, I've seen some open source projects abandon the interests of their initial core community.  What I see here is a long standing feature request that was not fulfilled for nearly 20 years overall (if you count gqview too). One of the devs in this thread stated that it's not in line with core goals. That may be true but it's obviously something people have been wanting for a while, feel strongly about and even willing to pay for. I'd like to remind the devs that often times the reason why a project gets forked or even abandoned is because the devs do not adapt to the needs of their user community, even if they don't share the same needs. I'm glad to see this time there was a positive outcome, but looking through this multi-year thread I could almost see this one going the way of the "project fork". I love geeqie and want to see it continue to be developed. I applaud your efforts to continue to maintain it and the addition of this feature. Thank you.

**Comment by caclark** [comment]
I find it difficult to decide what is worthwhile and what is not.
The importance of a feature request issue is not easy to judge, because there are so few people commenting on them - frequently just one person.

Even the animated gif, the subject of this issue, is a bit confusing to me. There were requests for this feature, and Christian Heckendorf came up  with a solution. But the implementation reads directly from the file, and thus causes Geeqie to freeze until the whole file is read. Very small .gifs are ok, but files of a few megabytes or so have a noticeable effect. So is anyone using this feature? Do users only load very small gifs?  But no-one has complained - so I guess there is no problem.

If people think that an issue is of importance to them, it would be useful if they could hit one of those emoticon things to let others know what is important.

**Comment by tomaszg7** [comment]
> But no-one has complained - so I guess there is no problem.

Just for the record - I did complain and it resulted in https://github.com/BestImageViewer/geeqie/commit/d599fbc9761f0aed6be21d1e303c6a72f6307335

I don't really understand @deltaray post. Who was supposed to fork Geeqie if there was noone who wanted to implement the feature? There was no problem with Geeqie maintainer refusing to merge a submitted patch. I think Geeqie is one of the project where it is the easiest to get your contribution accepted (sometimes it is too easy, some bugs creep in, I know I contributed to several so far ;) ).

**Comment by caclark** [comment]
Hello Thomas
The code I was referring to is at line 381 of layout_image.c, which is where gdk_pixbuf_animation_new_from_file() is called. That's what causes the freeze.

It would be better (but more complex code) to use gdk_pixbuf_loader_new()  - the Description para. here:
`https://developer.gnome.org/gdk-pixbuf/stable/GdkPixbufLoader.html`

Well, maybe one day I'll fix it...

**Comment by tomaszg7** [comment]
I think that the issue I was refering to was also related to the same call - any file had to be read fully before it would be displayed even if it was not an animated GIF. As you said, for small GIFs impact was negligent, but for huge CR2 or TIFF files, it was not

**Comment by deltaray** [comment]
As I said, I wasn't trying to criticise or offend the developers. I think you're doing a great job with geeqie. I just wanted to try to provide some user perspective based on the history of this issue. @caclark, you made a good point with the implementation can be tricky because the default behavior of loading gifs could be implemented in different ways and gifs have definitely gotten bigger over the years. 

@tomaszg7, to answer your question of who would fork. I don't know, I'm just saying that sometimes when a feature request goes unanswered for a while, someone comes along and if the devs don't accept their patch, a fork may happen, which I think can be a loss for the community.  In this case the patch was accepted, which is great, but it could have gone the other way.

Also regarding "no-one has complained", that may be true and may continue to be true, but new versions take time to get into repos, where majority of users get their software from. 1.2.2 is the latest available from the repo I use. Sometimes it can be several years before a change in source is picked up by the "public".
