### ISSUE TITLE
SVG files don't scale correctly.

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#255]
I know this is probably because you're using Gtk, and it converts it to a raster image when you load the file, but vector graphics should be able to scale (that's the point of using vector graphics, isn't it? :)

I've tried this in a few image viewing programs, and the only ones that seem to scale SVG files without conversion are Vector Image editors/creators.  It would be nice to have this feature in an actual (lightweight/fast) image viewer.

I don't know how you handle image loading, and this is probably not high-priority, but if anyone gets around to it, this functionality can be 'fixed' with the rsvg library.  At least that's how I'd do it in Python: 
http://cairographics.org/pyrsvg/

Reported by: planck

**Comment by caclark** [comment]
As commented above, this isn't really a Geeqie problem. Geeqie uses libpixbufloader-svg, and is limited by the capabilities of that library.

**Comment by caclark** [comment]
> , I could roll up my sleeves and give it a go.

There are a number of issues listed here relating to svg, so I think there are plenty of people who would be grateful for any contributions you make.

I have no idea what the problem is - there is a comment I made in #188, and there is a comment at line 504 in image-load.c, but that is the extent of my knowledge.
