### ISSUE TITLE
add support for loading remote URLs

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#283]
It might be useful to allow displaying remote URLs.

Forwarded from http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=240132

Reported by: nijel

**Comment by caclark** [comment]
I guess the address box could be search for the string "http:" and libcurl used to get a file.
But I think it would rapidly get complicated, and maybe not that useful.

To easily get an occasional file from the web I call this script from a .desktop file:

`#!/bin/bash

clipboard=$(xclip -out -selection primary)

downloadtype=$(echo "File!Folder")
selection=$(yad --width="300" --title="Download web file" --text="Download web file:" \
--form \
--field="Download Type":CB \
--field="Web address:":TXT \
"$downloadtype" "$clipboard" )

if [[ -z $selection ]]; then
  exit
fi

IFS=\| read downloadtype webaddress <<< "$selection"

set -- $(ls -d /tmp/geeqie_web_files*)

if [[ -d $1 ]]; then
  tempdir=$1
else
  tempdir=$(mktemp -d geeqie_web_files_XXXX --tmpdir)
fi

if [[ $downloadtype == "Folder" ]]; then
   xterm -e wget --no-directories --recursive --directory-prefix=$tempdir \
    --accept jpeg,jpg,bmp,gif,png,webp $webaddress &
else
   xterm -e wget --directory-prefix=$tempdir $webaddress &
fi

tmpfile=$(mktemp --tmpdir=$tempdir geeqie_tmp_XXXX.jpg)
geeqie --remote file:$tmpfile
rm $tmpfile
`
It's basic, but works.

I suggest this issue is tagged as "wontfix" and closed.

**Comment by caclark** [comment]
Implemented in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=a19ae63158adfa45d9f66e089d1eb8814476f8da
