### ISSUE TITLE
include pdf-view

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#322]
I find it a very valuable feature, if geequie could also display / view or at least preview .pdf-Files, as many scanners provide them.

Reported by: mfueh

**Comment by caclark** [comment]
As perhaps implied by the above feature request, I have also used a flatbed scanner to scan a document into pdfs. But in those cases I usually simply use Evince to view the resulting pdf files.

The times when I have needed to use Geeqie to view a pdf are when e.g. someone has digitised an old workshop manual into a variety of jpegs and pdfs.
I have created a Geeqie plugin to call Evince so I can view the pdfs, but it would be useful if a thumbnail was also displayed.

I guess libpoppler/ghostscript/whatever could be used to create thumbnails, and also possibly create a full-size image of the first page.
The method used by Tomasz Goliński to display MOV files could also be used - i.e. specify in Preferences an external program to be called when left-clicking a pdf file.

But the question is: Is this too far away from Geeqie's main purpose of displaying photographic images?

**Comment by tomaszg7** [comment]
It should be feasible (and quite easy) provided there is a low overhead lib to provide support for generating preview. 

We could probably think about a list of formats Geeqie could reasonably be expected to handle, including e.g. .cbr/cbz (https://github.com/BestImageViewer/geeqie/issues/299). BTW audio files are already handled via ffmpegthumbnailer - it is enough to add them as video files to the filter list. If they have e.g. embedded cover, it will be displayed.

**Comment by caclark** [comment]
Attached are two .diffs that allow Geeqie to show the first page of a pdf file.
One problem is that although libpoppler is supposed to be thread-safe, unless there is a lock, seg faults occur.
Clearly there is something that I don't understand here.
The other problem is that it doesn't compile with GTK2...
I guess in time I will get around to solving these problems. In the meantime, it works with GTK3 - as far as I can tell.
[pdf_viewer_1.diff.gz](https://github.com/BestImageViewer/geeqie/files/2199159/pdf_viewer_1.diff.gz)
[pdf_viewer_2.diff.gz](https://github.com/BestImageViewer/geeqie/files/2199160/pdf_viewer_2.diff.gz)

**Comment by marcelpaulo** [comment]
It's working really fine with [43f7481@geeqie.org](http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=43f7481548feb8b6f3a82af9efe9f522011678d7) !

To open PDFs (actually, any file), I first added to _~/.mailcap_
```
application/pdf; zathura %s; edit=masterpdfeditor %s
```

Of course, `zathura` can be replaced by any PDF reader, and `masterpdfeditor` for any PDF editor.

I then created _~/.config/geeqie/applications/open.desktop_, and associated it to keyboard shortcut `ctrl-o`:

```
[Desktop Entry]
Type=Application
Name=open
Exec=run-mailcap --action=view %F
Icon=preview-file
Categories=X-Geeqie
OnlyShowIn=X-Geeqie
X-Geeqie-Verbose=false
```

To edit PDFs (once again, any file), I created _~/.config/geeqie/applications/open.desktop_, and associated it to keyboard shortcut `ctrl-e`:
```
[Desktop Entry]
Type=Application
Name=edit
Exec=run-mailcap --action=edit %F
Icon=document-edit-symbolic
Categories=X-Geeqie
OnlyShowIn=X-Geeqie
X-Geeqie-Verbose=false
```

**Comment by caclark** [comment]
Note that if you are a mouse-user, you can also put an icon on the toolbar for any of the .desktop files.
(Make sure there is an entry in the "Icon=" line)

**Comment by marcelpaulo** [comment]
Oh, I didn't know the toolbar could be customized. Good tip, thanks !

I went ahead but hit an issue. All _.desktop_ files have a valid `Icon=`:
![image](https://user-images.githubusercontent.com/10074769/43102341-3f073b3c-8ea1-11e8-8743-badf213dba33.png)

but they're not shown in `Add Toolbar Item`:
![image](https://user-images.githubusercontent.com/10074769/43102411-7624a122-8ea1-11e8-8d0d-ce2a8f3215a1.png)

However, I went ahead and added them anyway, and the icons did show up in the toolbar:
![image](https://user-images.githubusercontent.com/10074769/43102501-b05081f4-8ea1-11e8-816c-72a09d0544a3.png)

If this is a bug, would you like me to open a separate issue to track it ?

**Comment by caclark** [comment]
> If this is a bug, would you like me to open a separate issue to track it ?

Yes, this is a bug :-(
It would be good if you would open a separate bug report. Thanks.

**Comment by marcelpaulo** [comment]
> It would be good if you would open a separate bug report

#625

**Comment by caclark** [comment]
Implemented in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=43f7481548feb8b6f3a82af9efe9f522011678d7

**Comment by caclark** [comment]
Latest commit allows viewing of multi-page pdfs.
Use \<control\>page-up and \<control\>page-down to scroll through the pages.
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=b51170db7f2410a938867f3e1dcd8dc1dd2e6c27

**Comment by tomaszg7** [comment]
Several issues/ideas/problems: 
1. I don't see a way to add toolbar icons for next/prev page or map these actions to mouse buttons.
1. Could be good if there would be a way to use mouse to switch pages. Maybe extend newly introduced configurable button dialog to give the possibility of remapping the wheel, so that one could use wheel up/down (or wheel+ctrl) to switch pages.
1. Most of the pdfs I tried have transparent background. It makes it difficult to read.
1. Pdfs are generally rendered in quite low resolution. It would be the best if it could be made adaptive (i.e. resolution increases upon zooming) but that probably is not possible without major code changes. In my case standard A4 pdfs are rendered in 612x792 which is much too small for any practical purpose other than quick preview.

**Comment by caclark** [comment]
> Pdfs are generally rendered in quite low resolution

I am not sure what to do about this. Evince will always look better when displaying a text pdf, because the text is displayed as text but Geeqie shows text as an image.
A pdf file containing small images is displayed the same in Evince and in Geeqie.

Other points fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=5e259bb11bfc65b490cd79eccd765a0f05d464b5

**Comment by tomaszg7** [comment]
> I am not sure what to do about this. Evince will always look better when displaying a text pdf, because the text is displayed as text but Geeqie shows text as an image.

Well, that is rather not precise. Both Evince and Geeqie display a text pdf as image since that's only thing you can really display ;) The only difference is that Evince changes resolution as needed when zooming the image. It re-renders the vector data as a new image.

I don't remember how exactly the requested width and height were passed to image loaders, but there was something dodgy about it at some point. In principle, it might be possible to call proper set_size functions on resize. Loaders of raster graphics would ignore that since they already render image full size, and loaders for vector graphics would re-render it with new constrains. I don't know how feasible it is though. Easier way would be just to make a render DPI for vector data a configurable option.
