### ISSUE TITLE
"Sort by" buttons in file view

### ISSUE THREAD

**Issue by m-guggenmos** [BestImageViewer/geeqie#429]
Hi,

i am very frequently searching for files either by name or by modification date and the current way is a bit cumbersome with two/three button clicks (e.g. Sort by -> Date -> Ascending). It would be a bit easier if the file view had these clickable column buttons for Filename, Size and Date, etc. that are standard in many file explorer panels. For instance, click on the Filename column button and it sorts by filename, click again and it sorts reverse. The same would be nice for the folder view. Has this feature been discussed?

Cheers
Matthias

**Comment by caclark** [comment]
The above comment is a little old, but nevertheless....
The suggestion is problematic because of the possible number of columns, and because you can only see them in list view, and not in icon view.
On the status bar on the bottom of Geeqie's window is a section displaying the current sort order. Click on it and you will be presented with a selection menu. Although it is still two clicks to sort, I find it much quicker than mousing through the menu.

**Comment by caclark** [comment]
No further comment, so I guess this can be closed

**Comment by Lovewyrm** [comment]
I'd love to have this feature, too, even if it were just in list view.
"Best imageviewer" status is impossible to attain if you can't sort the albums, only the files therein.

So, yeah... would be really handy to have albums that recently changed at the top...

**Comment by caclark** [comment]
> would be really handy to have albums that recently changed at the top

I don't understand what you mean by the word "album". Are you referring to a folder (or sub-directory)?

**Comment by Lovewyrm** [comment]
My bad for being obtuse.

Anyway, any directory, really.
Starting at /.

As it stands directories are sorted alphabetically, meaning the directories CAN be sorted in some fashion.
It would be great if there were other options, like "date".

Regardless:
>The suggestion is problematic because of the possible number of columns, and because you can only see them in list view, and not in icon view.

Is it truly problematic?
Why would it only work sorted alphabetically, and not any other way, provided everything is sorted the same?

To clarify, right now, everything works, right? Despite the possible number of columns or whatever, geeqies functionality is, well, intact with its default alphabetical sorting.

If alphabetical sorting works, why would any other sorting not work, provided it were as 'global' as the alphabetical one.
As in, not just one single directory sorted by access dates, but everything, as if the default alphabetical sorting were completely replaced by a new one.

Would this truly break the entire program?

**Comment by caclark** [comment]
I think you are referring to sorting the folder pane, rather than the files pane.
The sort order there can be changed - there are already options for case and natural order.
So I assume sorting on mtime is also possible.
But note that mtime for a  folder is not exactly the same as for a file.
If a file is added to or removed from a folder, the folder mtime is updated.
If a file within a folder changes, the folder mtime is *not* updated.

**Comment by Lovewyrm** [comment]
I just realized that this issue is about the files pane, my sincere apologies.

Anyway, yeah, the folder pane I guess? 
Or "tools" pane (as 'configure this window' suggests) ? 
Is this a new setting then? I'm on 1.5.1.

I have no sorting options for the folders. 
https://i.imgur.com/zUBTV3O.png

**Comment by caclark** [comment]
The case and natural sort options are in Edit/Preferences/Files.
I assume they are there, and not in a popup,  because they are not likely to be changed frequently by the user. It avoids unnecessary clutter on the popup menu.

What is your opinion of the usefulness of sorting folders on mtime, given the limitations of that option?

**Comment by Lovewyrm** [comment]
Mmm, I see no real change happening when I tick the natural sort option, but thank you for the directions anyway.

As for the usefulness, I'm an artist and I have a folder for references, as well as one for artists I like.
I tend to download a bunch of their work in a batch and save it either into their existing folder or a new one.
This means the artists I've been interested the most are at the top when (reverse) ordering for time.
Therefore, having that in geeqie as well would make browsing the entire batches of them easier.

If it's just one updated folder then it's alright to pick it out by scrolling around the pane (since geeqie doesn't seem to have a filter there, or maybe I just don't see it or know how to open it), but if it's five or so then it starts to become a pain since the folder is rather large with many artists.

At the moment I'm using a script that creates a geeqie collection, but that's often laggy for me.
Having the folders sorted like that 'natively' would be the most helpful since I grab those batches programmatically based on a few pictures I like and figure that the rest of the works must be equally appealing to me.

**Comment by caclark** [comment]
> I see no real change happening when I tick the natural sort option

It will depend on how you name folders. In your case using numbers in folder names might be relevant. Here is the function that is used:
https://developer.gnome.org/glib/stable/glib-Unicode-Manipulation.html#g-utf8-collate-key-for-filename

**Comment by caclark** [comment]
Attached is a .diff that permits sorting folders by date or name.
The function is only in folder list view (not tree view).
If anyone would like to try it and comment on its value...
[sort_folder_1.diff.gz](https://github.com/BestImageViewer/geeqie/files/4135171/sort_folder_1.diff.gz)

**Comment by Lovewyrm** [comment]
Thanks, I'll check it out!

**Comment by Lovewyrm** [comment]
Sorry for the delay, was not at home, but~
It works! Thank you so much, @caclark !

**Comment by caclark** [comment]
Name/Date sort implemented in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=e0b589e5cdaa96159d37118de347a80cde20ef41
