### ISSUE TITLE
Find Duplicates behaviour & suggested improvements

### ISSUE THREAD

**Issue by SimonDedman** [BestImageViewer/geeqie#435]
Unless people know a better way, it seems the way to use the Find Duplicates (hereafter FD) tool for contents of a folder are:

Hit "D" to open FD window
Alt-Tab back to Geeqie
Click sidebar to focus on an image
Ctrl+A to select all
Mouse-Drag all to FD button on taskbar, which brings FD to front, drop images there
Click "show thumbnails"
Click dropdown
Select "by Similarity"
Right click an image
Select "select group 2 duplicates"
Right click one of the selected group 2 duplicates
Click "delete"*
Close FD window

I propose the following improvements:
1. FD window is always on top of Geeqie? If it starts in windowed mode by default then one can drag files to it without having to drag via the taskbar to focus the FD window.
2. Hitting D with files selected brings up with FD window with selected files automatically populated.
3. Hitting D with NO files selected brings up with FD window with all files in the current directory automatically populated. (I think 2 & 3 would avoid the need for 1, to be honest)
4. An option in settings for FD to remember previous settings ('compare by' choice, thumbnail on/off, 'selection' choice).
5. An alternate option for FD to default to an option of user choosing (mine would be group 2 duplicates, similarity, thumbnails on. Yours might be something else)
- Hitting the delete key on the keyboard appears to do the same thing but the files aren't in the trash location and don't appear to have been deleted?
- Fix the delete key so it behaved the same was as right click > delete.
- Possibly some kind of delete confirmation dialogue option, separate from the standard delete key outside of the FD window, which would list files to be deleted in a fixed size scrollable box, then give OK (enter key) and CANCEL (escape key, which would bring you back to the FD window, only closing the dialogue box).

Thanks. I feel that the FD feature of Geeqie is one of it's (semi) hidden gems and possibly the best way to find & remove dupe images in Linux, but it's (slightly) hampered by clunky usability. I reckon that these (hopefully easy?) fixes would address that, and massively speed up the process of using it.

**Comment by caclark** [comment]
If you right click on a folder name, the pop-up menu has options for "Find duplicates" and "Find duplicates recursive". Both are populated with the folder contents.

Right click on a Collections window also has a "Find duplicates" menu item, also populated with the contents.

Drag-drop to both the dupes and collections windows is a pain on a small screen, because the window disappears behind the main Geeqie window. But if gtk_window_set_transient_for() is set, that window will always be on top of Geeqie - which also isn't always what I want.

I have set alt-A on my keyboard to set the currently-focused window to toggle "Always on top" - that works ok for me when dnd'ing.

**Comment by SimonDedman** [comment]
Thanks Colin. Certainly right clicking the folder & selecting FD that way, rather than dragging, ameliorates the window focus & dragging issues/faff.

The ability to 'remember last used' or 'set default' set of options for FD would definitely be cool though...

Thanks!

**Comment by caclark** [comment]
Sorry, I forgot to comment on the Delete key - I also have comments I don't know where else to put.

The Delete key function for dupes is documented in the Help file, although it is easy to miss - it is in a reference to Collections where the Delete key has the same function. In these cases the Delete key simply removes an item from the list - no files are deleted.

I would prefer not to have an important key like Delete changing meaning between windows.
I would suggest another key (intuitively the minus key would be good) for removing items from a list.
Although minus is also used for zoom, I don't feel a user would be confused when switching windows, and anyway, neither is a critical operation.
Nevertheless, due to its importance, I think that the Delete, Keypad Delete, and Control-D keys should be synonymous for all Geeqie windows.
 
But this is a decision for people who understand standards and human interfaces - or a general referendum.

**Comment by caclark** [comment]
Hello Simon
I do not think it worth doing any more in this area. If the Preferences "Custom Similarity" and "Rotation Invariant" were frequently used, it would make sense to put them on the duplicates window status bar - but no-one has complained yet.

By the way, there is a command line option:
geeqie --alternate
The code comments say this "hopes to reduce false positives". In a trivial test I made, this is so. If you need to know more about this option, unfortunately reading the code in src/similar.c is the only way.

**Comment by mowgli** [comment]
Well, Colin, I use them. :-) Especially the Rotation Invarian is a very powerful setting. However, I seems to miss the point where it is important for this issue.

On the other hand about deletion of doublicates, I am currently developing some feature to allow that to use on many, many hits at once.

**Comment by caclark** [comment]
"However, I seems to miss the point where it is important for this issue."  Es tut mir Leid..., I don't understand your meaning here.

My comments were about improving the usability of the duplicates function.

My point was that if "Custom Similarity" and "Rotation Invariant"  are parameters that are constantly being changed by the user during a session, it is difficult to keep switching to the Preferences page to change them. In this case it would be easier of these parameters were at the bottom of the duplicates page so that can be immediately changed (e.g. as for the "Compare By" drop-down).

However if these values are set once only and then never changed, they should be left on the Preferences page.
