### ISSUE TITLE
Delete to standard Trash directory?

### ISSUE THREAD

**Issue by SimonDedman** [BestImageViewer/geeqie#437]
One can configure the trash directory to be the user's wastebasket which seems intuitive where people would look first. The real location of this (rather than trash:///) is:

`/home/[username]/.local/share/Trash/files`

However the normal process of deleting files using e.g. thunar causes tiny .trashinfo files to be created in /Trash/info, containing original location and deletion date, which allows one to restore to original location through the wastebasket. It may be that thunar etc uses

`gvfs-trash your-filename-here`

to delete them. See [here](https://askubuntu.com/questions/523906/how-to-delete-to-trash-via-terminal-with-mv-command). Deleting directly to /files by entering that directory into Geeqie preferences means these aren't created and the user has to find the location to manually restore them to.

Please could an option be added in preferences > behaviour > delete > safe delete > folder:
'Wastebasket' radio button (default; which would use gvfs-trash [selected file list])
'Custom' radio button (would cause the folder tree dialogue to be active (un-greyed-out)

Thanks!

**Comment by caclark** [comment]
Using gvfs-trash is definitely a more 21st century solution than the standard Geeqie method. 
But it involves Gnome, XDG and probably other things I don't know about, so I have no idea how to implement it.
However, take a look at the Help file - External actions/External Editor Configuration. There you will see how to create a desktop file called geeqie-delete-command.desktop.
Insert "Exec=gvfs-trash %f" and things should work as you wish.

!! N.B. When I used the %F parameter, the deleted files disappeared  into some unknown bit-bucket. It would be best to first check the operation using some scratch files.

Also after editing a desktop file, shut down Geeqie and restart it. There were times when Geeqie appeared to be taking an earlier cached version of the file, rather than the latest one from the disk.

**Comment by SimonDedman** [comment]
Brilliant, thanks Colin. Looks like this method is resource minimal also: my previous method for some reason hogged a ton of resources using gvfs-trash.

Cheers!

**Comment by caclark** [comment]
Delete to trash is now part of the Geeqie code:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=eedf0ad8550ad5ed95a48d9770669b80bde66b5d
