### ISSUE TITLE
Consistency between repositories

### ISSUE THREAD

**Issue by russel** [BestImageViewer/geeqie#471]
The repositories https://github.com/BestImageViewer/geeqie and git://www.geeqie.org/geeqie.git appear not to be consistent, there are changesets in one repository not in the other, should these be mirrors of each other?

**Comment by lge** [comment]
On Wed, Feb 15, 2017 at 03:20:50AM -0800, Russel Winder wrote:
> The repositories https://github.com/BestImageViewer/geeqie and
> git://www.geeqie.org/geeqie.git appear not to be consistent, there are
> changesets in one repository not in the other, should these be mirrors
> of each other?


Right now (see date of this post), it looks like this:

+  [geeqie.org/master] Orientation commands and file selections
+  [geeqie.org/master^] Fix progress bar text
+  [geeqie.org/master~2] Move exif auto-rotate option to a menu
+  [geeqie.org/master~3] Fix #469: Exif rotation problems
+  [geeqie.org/master~4] Save position of tools window
+  [geeqie.org/master~5] Update documentation for orientation commands
+  [geeqie.org/master~6] Search on exif date
+  [geeqie.org/master~7] GIF animation settings
+  [geeqie.org/master~8] Fix compile warnings
+  [geeqie.org/master~9] Fix compile warning
+  [geeqie.org/master~10] Move duplicates options
+  [geeqie.org/master~11] Right-click menu separators
+  [geeqie.org/master~12] Temporary fix #459: GTK 3.20 drop-down
+  [geeqie.org/master~13] Fix #435: Remember duplicates settings
+  [geeqie.org/master~14] Fix #460: Multiple duplicates
+  [geeqie.org/master~15] Preferences: Open recent list maximum size
+  [geeqie.org/master~16] Rectangular selection
+  [geeqie.org/master~17] Revised Help documentation
+  [geeqie.org/master~18] F10 in Search window
+  [geeqie.org/master~19] Fix #447: Preferences Enable Delete key
+  [geeqie.org/master~20] Status bar tooltips
+  [geeqie.org/master~21] Command line option to print current filename
 - [github/master] Merge pull request #452 from xsdg/werror
 + [github/master^2] Add "-Werror -Wno-error=" to the default CFLAGS.
 + [github/master^2^] Fix GCC and Clang compile warnings.
-- [geeqie.org/master~22] Merge remote-tracking branch 'github/merge-requests/451'


Not too bad, really, and can still easily be merged.

Serveral possible ways forward:

* drop one or the other.

I don't like this option.
github makes the project much more visible,
geeqie.org makes it independent.
I'd like to keep both.

* keep both, and solve the "mirror each other" task
"occasionally", by merging stuff manually.

Um. We are programmers. We automate stuff.

* keep both, but "hide" the geeqie.org one,
and point/redirect it to github.
Mirror github in a "hidden" repo, in case you need
to "undo" that redirect at some later point in time.

I'm undecided here, I don't know what would be involved.

* keep both, and solve the "mirror each other" task
by adding appropriate "hooks" in generic git and/or github.

Technically, one solution could be to add both
pre- and post-receive hooks on geeqie.org.

pre-receive hook double checks with github
[does fetch (or even pull --ff-only) from github],
and rejects the current update if it would cause divergent branches,
so you would be forced to merge-in any github visible changes
that are not yet on geeqie.org, before pushing to geeqie.org.

post-receive hook would forward all changes to github.

Yes, small time window would remain where github could change
between "double check" and "forward new changes".

Unlikely to happen with the small number
of active developers geeqie currently has.

Can be reported, and manually dealt with.

* keep both, but make one "read only".

For example, all pushes go to github,
anyone trying to push to geeqie.org will be rejected
by some pre-receive hook, with an appropriate message
telling them to "git remote origin set-url github..." or the like.

Or the other way around, disable the web-ui "merge" and similar buttons, and
disable direct push to github, resolve pull request merges and other stuff
on geeqie.org first, and push to github only from geeqie.org.

Other thoughts?

If you think that would be useful, I can cook up such git hooks.

Cheers,

    Lars

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Am Mi den 15. Feb 2017 um 14:04 schrieb Lars Ellenberg:
> On Wed, Feb 15, 2017 at 03:20:50AM -0800, Russel Winder wrote:
> > The repositories https://github.com/BestImageViewer/geeqie and
> > git://www.geeqie.org/geeqie.git appear not to be consistent, there are
> > changesets in one repository not in the other, should these be mirrors
> > of each other?
> Right now (see date of this post), it looks like this:
[...]
> Not too bad, really, and can still easily be merged.

Master is git://www.geeqie.org/geeqie.git. Github is just a side push.

However, I have no Key of Omari so he cannot push tho the master.

> * keep both, and solve the "mirror each other" task
> "occasionally", by merging stuff manually.

That is the way it is done currently.

> * keep both, and solve the "mirror each other" task
> by adding appropriate "hooks" in generic git and/or github.

I do not know how to programatic push to github without puting my key
without password on the server.

> Or the other way around, disable the web-ui "merge" and similar buttons, and
> disable direct push to github, resolve pull request merges and other stuff
> on geeqie.org first, and push to github only from geeqie.org.

That I would prefer. But this is my personal preferences.

> If you think that would be useful, I can cook up such git hooks.

If you have a solution how to push to github without giving away the ssh
key...

Nevertheless, I will look at a merge in the night today.

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAlikVU8ACgkQpnwKsYAZ
9qy93wv/Smv+annALDVCofga9g/e289WcXuGNjv6/AXd3F4AH0zrS171NHefmCLt
3n4oyFZJYv8pBGi8gzwkhNAAp60oYvQRatpcan3gErbN/VulO42QrdzZbldL7GIo
SeBPT5Val3b6we8ppGaEtarGTo79LNlzpWs5xF9JROvaSqXGo9+Zdbj3om+QZqu/
Yr9XbF9IFizD+8QJ978Vf2wnMQyFbndm8x7GKt0wok4jknZjuG+EkVYWuuLWZmFm
0e9SQtHlZIM6HgWHiauEMLobv1BgVugBPw5Lsaket+C2QFOUyVK7JIMsHgUp5AGh
Pv4l3Z3FqhDcbbrl5aicLlQvsrcOQDQJtt57fqKSVVVjtndO1J+F2ai47Ama3Vnw
bzTEod+UepJRfSGiVdzJUN3pdAE62y3ysDjBiisJxTLSWerRb53cCoOWubzeO2Es
vZ5XheVJwn9p9ahwodbsPCyBjOkHkW9IcWEL4hoAh1vt7LbCXstMZkaPaw37ob0I
QicTMAH6
=KyhF
-----END PGP SIGNATURE-----

**Comment by stefantalpalaru** [comment]
> I do not know how to programatic push to github without puting my key without password on the server.

They want your public key, not your private one. It's safe to give it to them.

**Comment by n3storm** [comment]
Hi, I have been a long time user of Geeqie and now I am back. I am glad is still maintained and faster than ever.

If you are interested in maintaining geeqie.org site, even revamping it to look modern I offer my self to host and maintain the site.

Drop me a message to hola@estudionexos.com in case I don't see github notification.

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi Néstor,

Am Mi den 12. Apr 2017 um 18:32 schrieb Néstor Díaz Valencia:
> Hi, I have been a long time user of Geeqie and now I am back. I am glad is still maintained and faster than ever.
> 
> If you are interested in maintaining geeqie.org site, even revamping it to look modern I offer my self to host and maintain the site.

If you are interested, just look into the web subdirectory, modify it
and drop a patch to the mailinglist (in Cc). Alternativelly you can do a
pull request on github but this will not be notified by that many
people.

If the community decide to use it, I will put it to live. Alternativelly
you can post some screenshoots first.

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAljvOjwACgkQpnwKsYAZ
9qzvsQv/dIEmTGDmoI9Qup4ZEMiALqAyhSotLseDQ6RQUfUluFZ4GEmDjZtOz1gr
wz8IJX6l8mEvhjaeoMO3X2rcbVDeUphC6Q5QgxiJ+Be0J1M6T8ZKyQCo9h0FRVAy
qtTCik8k7E72ehSYbe8CZBlcNI9+mEmmBF+4mZCC11nVIGXCS5+R446WYrs3NcNN
uSM//U+BR13Nrb0+Wx6kUd5UWb0JbsM2HVIs9KyXyrjE1ydUlBMH0/tPmeMw8Da/
TSytfKhSsQGwmD85qTJPcS79YPayov4wPABPEVCwMNnjKusxtWDrztdraaZd1iNa
UOCMu3i7NlPar75MCHESld8txUkkfTrBbfVcBB3mSj68IQl54OsyjgAbxpcTgFlO
Gb/6D59nL3qefwhZInNSFh2C1Np2ie2nqLm4L6w2znuWLUshP1dW45ixHTMo8q/q
6uklY93MqI7nmnvgzSoklNJT1mUu23kHbrLqMt/MudFORhwNoa0Kgeg7LF/5gHSC
BEVTeVsA
=D+6Y
-----END PGP SIGNATURE-----

**Comment by mowgli** [comment]
Hi,

Just letting you now I am building a prototype of the site and will 
publish it at one of my domains so all the team can have a look and give 
opinion.

Thanks!

Néstor


El 13/04/17 a las 10:43, Klaus Ethgen escribió:
> -----BEGIN PGP SIGNED MESSAGE-----
> Hash: SHA512
>
> Hi Néstor,
>
> Am Mi den 12. Apr 2017 um 18:32 schrieb Néstor Díaz Valencia:
>> Hi, I have been a long time user of Geeqie and now I am back. I am glad is still maintained and faster than ever.
>>
>> If you are interested in maintaining geeqie.org site, even revamping it to look modern I offer my self to host and maintain the site.
> If you are interested, just look into the web subdirectory, modify it
> and drop a patch to the mailinglist (in Cc). Alternativelly you can do a
> pull request on github but this will not be notified by that many
> people.
>
> If the community decide to use it, I will put it to live. Alternativelly
> you can post some screenshoots first.
>
> Regards
>     Klaus
> - -- 
> Klaus Ethgen                                       http://www.ethgen.ch/
> pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
> Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
> -----BEGIN PGP SIGNATURE-----
> Comment: Charset: ISO-8859-1
>
> iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAljvOjwACgkQpnwKsYAZ
> 9qzvsQv/dIEmTGDmoI9Qup4ZEMiALqAyhSotLseDQ6RQUfUluFZ4GEmDjZtOz1gr
> wz8IJX6l8mEvhjaeoMO3X2rcbVDeUphC6Q5QgxiJ+Be0J1M6T8ZKyQCo9h0FRVAy
> qtTCik8k7E72ehSYbe8CZBlcNI9+mEmmBF+4mZCC11nVIGXCS5+R446WYrs3NcNN
> uSM//U+BR13Nrb0+Wx6kUd5UWb0JbsM2HVIs9KyXyrjE1ydUlBMH0/tPmeMw8Da/
> TSytfKhSsQGwmD85qTJPcS79YPayov4wPABPEVCwMNnjKusxtWDrztdraaZd1iNa
> UOCMu3i7NlPar75MCHESld8txUkkfTrBbfVcBB3mSj68IQl54OsyjgAbxpcTgFlO
> Gb/6D59nL3qefwhZInNSFh2C1Np2ie2nqLm4L6w2znuWLUshP1dW45ixHTMo8q/q
> 6uklY93MqI7nmnvgzSoklNJT1mUu23kHbrLqMt/MudFORhwNoa0Kgeg7LF/5gHSC
> BEVTeVsA
> =D+6Y
> -----END PGP SIGNATURE-----

-- 
   http://www.estudionexos.com
   hola@estudionexos.com
   tlf. 983 070 900

**Comment by mowgli** [comment]
Hi Klaus and all Geeqie devs:


This is WIP:

http://geeqie.estudionexos.com/

Icon is a mix of two Tango icons (file image icon modified by me) I 
propose this icon for distribution. License is same as Tango icons.


TODO:

Image optimization: Background images are slow yet cause they are 
retrieved from a third party site (no problem with copyrights) 
Pexels.com https://www.pexels.com/photo-license/

History section background image makes difficult to read text in some 
resolutions.

More screenshots/screencaptures.

My setup is in Spanish so some Geeqie literals appears in Spanish. If it 
is too noticeable I made need to remake screencaptures.


QUESTIONS

What to do with online manual (host and rework with screenshots? remove 
from site?)

Do we have to highlight something I've missed? Features order is correct?


REQUEST

If anybody would like to contribute with original 
screenshots/screencaptures and background images please contact me.


Let me know what you think so far.

Cheers,

Néstor


El 13/4/17 a las 10:43, Klaus Ethgen escribió:
> -----BEGIN PGP SIGNED MESSAGE-----
> Hash: SHA512
>
> Hi Néstor,
>
> Am Mi den 12. Apr 2017 um 18:32 schrieb Néstor Díaz Valencia:
>> Hi, I have been a long time user of Geeqie and now I am back. I am glad is still maintained and faster than ever.
>>
>> If you are interested in maintaining geeqie.org site, even revamping it to look modern I offer my self to host and maintain the site.
> If you are interested, just look into the web subdirectory, modify it
> and drop a patch to the mailinglist (in Cc). Alternativelly you can do a
> pull request on github but this will not be notified by that many
> people.
>
> If the community decide to use it, I will put it to live. Alternativelly
> you can post some screenshoots first.
>
> Regards
>     Klaus
> - -- 
> Klaus Ethgen                                       http://www.ethgen.ch/
> pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
> Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
> -----BEGIN PGP SIGNATURE-----
> Comment: Charset: ISO-8859-1
>
> iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAljvOjwACgkQpnwKsYAZ
> 9qzvsQv/dIEmTGDmoI9Qup4ZEMiALqAyhSotLseDQ6RQUfUluFZ4GEmDjZtOz1gr
> wz8IJX6l8mEvhjaeoMO3X2rcbVDeUphC6Q5QgxiJ+Be0J1M6T8ZKyQCo9h0FRVAy
> qtTCik8k7E72ehSYbe8CZBlcNI9+mEmmBF+4mZCC11nVIGXCS5+R446WYrs3NcNN
> uSM//U+BR13Nrb0+Wx6kUd5UWb0JbsM2HVIs9KyXyrjE1ydUlBMH0/tPmeMw8Da/
> TSytfKhSsQGwmD85qTJPcS79YPayov4wPABPEVCwMNnjKusxtWDrztdraaZd1iNa
> UOCMu3i7NlPar75MCHESld8txUkkfTrBbfVcBB3mSj68IQl54OsyjgAbxpcTgFlO
> Gb/6D59nL3qefwhZInNSFh2C1Np2ie2nqLm4L6w2znuWLUshP1dW45ixHTMo8q/q
> 6uklY93MqI7nmnvgzSoklNJT1mUu23kHbrLqMt/MudFORhwNoa0Kgeg7LF/5gHSC
> BEVTeVsA
> =D+6Y
> -----END PGP SIGNATURE-----

-- 
   http://www.estudionexos.com
   hola@estudionexos.com
   tlf. 983 070 900

**Comment by caclark** [comment]
Hello Néstor
I am very impressed with your design - this is light-years away from the Sourceforge page.
I would like to make some comments, which I hope you will not find too critical.

I would prefer the official release of your design to coincide with the next official release of Geeqie itself. There have been a couple of additions to the repo since the current release that make a significant improvements to the usability of Geeqie.  I don't think it makes sense to push the advertising of the current release when there is much better to come. 

Would it be possible to link the video clip to a YouTube clip? It would be very useful to be able to view the video in high-resolution full-screen mode.

The video should also include views of the folder shortcuts/bookmarks pane, and also the Copy/Move conflict resolution dialogue (and maybe the on-the-fly renaming).

Perhaps also a brief view of GIF animation, a sample Pan View, and the GPS map.

There should be a link to a copy of the Help file - the Help file isn't too wonderful, but it maybe would help someone who is looking for a particular feature.

I don't think Printing should be referenced - that seems to be drifting towards the unsupported state.

I assume (if all goes well) that this will end up as the main page of geeqie.org. But there should also be a link somewhere to the git repository of geeqie.org.

The Version History entries should have links to the geeqie.org pages where the tars are held.

In the How To Contribute section, delete the second sentence. The fancy web-design is already in good hands...

[My personal view is that it is not necessary to include comments that are critical of Sourceforge - i.e. the reference to malware - the comments may be true, but.... that's just my opinion]

Typographical errors:
"focused on speed and image previewing and organising" -> "focused on speed, image previewing and organising"
"Organize without loosing space" -> "Organize without losing space"
"Check Preferences menu" -> "Check the Preferences menu"
"Read de manual" -> "Read the manual"
"Check this project history" -> "Check the project history"
"You are now browsing the project's official and only actual website" -> "You are now browsing the project's only official website"
"report bugs: https://github.com/BestImageViewer/geeqie" -> "report bugs: https://github.com/BestImageViewer/geeqie/issues"
"report bugs" -> "bugs and feature requests"

**Comment by n3storm** [comment]
Hi @caclark 

Thanks for correcting web contents and suggestions, I find them most great. I would like to start implementing them ASAP.

I don't think I completelly understand: The Version History entries should have links to the geeqie.org pages where the tars are held. But I think the overall idea is to link website stronger with Github (github links, badges, etc) Am I right?

If we are going to work with this code as web site base should we add HTML and resources to this repo or maybe create another one? It will be easier to follow suggestions and fixes instead of me collecting stuff from comments ;)

Cheers

**Comment by caclark** [comment]
Hello Néstor 
I have a couple  more comments, but please take them as nothing more than my opinions (whatever phrasing I have used).

1. geeqie.org - github
Geeqie.org is the "advertising page" that attracts new users. It also hosts the main repo, but most users will not see that. 
GitHub provides essential tools for users to log bugs and for developers to track fixes (maybe...).
I think they will both continue in parallel.

2. The current web page is a folder within the repository. When your design is finished I guess it will replace the existing one. Until then I don't know the best way to progress. I've attached a git-diff, which is the easiest way for me to suggest changes at the moment.

3. If possible I would like to see a language option - even if it is only Spanish/English, that is a good start.

4. The Features section on www.lynapp.com looks to me to be a good way to give more detail to potential users.

5. The situation with the code, packages and version history is a big, big problem. No bug fixes are back-ported to earlier versions. Some of the packages available are back at v1.0. But i don't know how to create packages, or get get distributions to use the current sources.
I thought a bit more about this problem - I now think that references to tars of earlier versions should not be supplied. If someone is going to compile from source, the latest version is a much better choice. But that may make problems with dependencies.

6. You don't like my screenshots  :-) ? I don't like my screenshots either. But they are an easy way to give people who don't speak English an overview of the program.

7. It would be better that any screenshots or clips use the latest version from the repo, so that the representation is consistent.

8. The attached git-diff is only a suggestion for some changes (and I don't understand html!) ...

[index.zip](https://github.com/BestImageViewer/geeqie/files/1254528/index.zip)

**Comment by n3storm** [comment]
@caclark I understand your points. 

1. Please poke me if I get out of project scope.

2. I am going to create a temporal repository here in github for interested people to contribute. I am not a git expert so not sure if it will be easy to merge everything back here. On the other hand I don't want all Geeqie history just for a website so I will start from an empty repository. I will sync this new repo with the development site at http://geeqie.estudionexos.com to see changes.

3. If we are going multilanguage I suggest we use a static site generator that help us with site maintenance and help language collaborators. I have a couple of options I will evaluate and comment here.
Also, this will help solving your point 8. as with a static site generator you can help contributing in Markdown language.

4. Great.

5. I have found some (not working now) javascript ways to ready Geeqie releases atom feed and github project badges so we can link together as much as needed html site with github real time information and avoid the "oh, forgot to update geeqie.org information with new release" and also avoid duplicated content.

6. :D yes we will go as much as graphic as we can. The youtube videos idea haven't fade away :)

7. This is something I have in my todo as I am using Debian 9 packages and havent compiled Geeqie from source yet.

8. Thanks! 

Let's move! Please confirm points 2. and 3. are okay for you.

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Am Mo den 28. Aug 2017 um 10:02 schrieb Néstor Díaz Valencia:
> 2. I am going to create a temporal repository here in github for interested people to contribute. I am not a git expert so not sure if it will be easy to merge everything back here. On the other hand I don't want all Geeqie history just for a website so I will start from an empty repository. I will sync this new repo with the development site at http://geeqie.estudionexos.com to see changes.

Well, you can utilize git-subtree to split a web directory out to a
different repository and allow to join it in later on again. This is
pretty nice.

> 3. If we are going multilanguage I suggest we use a static site generator that help us with site maintenance and help language collaborators. I have a couple of options I will evaluate and comment here.
> Also, this will help solving your point 8. as with a static site generator you can help contributing in Markdown language.

For multilanguage stuff, the html files could just use a name in the
form ...html.de or ...html.en and so on. Apache is taking the right one
from the proper language header in request.

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAlmlNSMACgkQpnwKsYAZ
9qzqewwApvYcV9FxXMpBQNRH4jBgQNmEuuL2ibRomES1ko6cskE7YDzqY212RmrU
jrrXbemTzhlab5GuW0gtO6TixKTiY66Z7bgu44d/l+OJdpHxGU3gi86xypf2Xjef
1WwXsaCuOrXNC5yvkLXBNVOY/QigcOz5K4j8hlcngkQigPyJFnB5Kla1r0+6Rauy
YynjoDfNtIm8DN4eBrtfsXDyC81vszW+z1fcCDAqKXlXqLheNqUAgvxumyg91e65
uCMjtHlCno4r5oEBDdTHs+Sn/Dt7nFeSJli61kPzK+8tRT61tZNDjhSIrBph3ap8
CdZAiVvPHGQwJcmmivY1dbV3LYkDO2zAPE6UI8RkNMScH5HMD46Y3XnVaw51OE2L
NDqHmUCKW7PpFSbvMwdCvYNOOP7AkZBq9SVTYkOXk6KaQneEHVKU0PlhJSbv5L/E
mLecj1RaT5w08vKvY79LjEpVWfrOCYtPf7xiYqNqUjkh141t+XfU+fidK5E+a3Pf
LX+XR8A4
=agHz
-----END PGP SIGNATURE-----

**Comment by n3storm** [comment]
>  Well, you can utilize git-subtree

Never done it. Will read about it.

> For multilanguage stuff, the html files could just use a name in the form

Anyway we need something to manage multiple sites and reuse html styles, galleries, etc so language sites doesn't feel different and everything is easier to maintain and contribute.

I want to give a try to Nikola https://getnikola.com/ What do you think?

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Am Di den 29. Aug 2017 um 10:52 schrieb Néstor Díaz Valencia:
> I want to give a try to Nikola https://getnikola.com/ What do you think?

I don't know. I use wml[0] usually. It might be a bit old style but I
like it. This nikola sounds similar, if you feel well wit it... :-)

Regards
   Klaus
[0] http://www.shlomifish.org/open-source/projects/website-meta-language/
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAlmlYVgACgkQpnwKsYAZ
9qwygAv/SBhar0adYMAfEyUUvl9DJA9Eg/qS8tyYb3GYxPogGhfrYRtIxQd4saSb
H8VPnYs+ZwwIq5U9XZuPcPj1fC6jZUf1Za7m+eZXtvqDQZKZg3r53XTUdux0sI1m
MNPZiJvGkGM8ROWECPSrO9f4iTpsV5cX0N+8JDcIwpX8WOFuvxOLLGi98DlJW/oP
Mg/UxvnPffP4ZgejusRV1kpGjZLMPJ2K8JZLR8x8uSB47Zn7NBufpR6PeghF8A1G
cYTfDuoGDW9NbZs6NjFR2Z29u+ISzCfdNCatKM3e5PwDG0T+rjYNJC3WbceWbNiU
Vmqw7CIWaI09rRXEmpm4s4RzRhaSaBCj0dtnEDxOwFeg/XHpPDSxtvd8S/mM1wEt
W3Q2RlEAuthSNoCKFBrwoL1NKHCcWpZHMS13DwCAdClaDpS8tc9YP+NqOwCBCZIc
XjFAuQTGY/+hZJdBMm8Abz2jL+N8OXhFiQjnGbfC83gNiNLN+QyKyUB7wqDrBSfc
mImVoQNQ
=yyk3
-----END PGP SIGNATURE-----

**Comment by mowgli** [comment]
Closing as the original request will never be fully closed. Github is only a slave repository.

The website discussion should be followed in #226.
