### ISSUE TITLE
‘Copy path’ and ‘Delete’ are too close in the drop down menu

### ISSUE THREAD

**Issue by deterenkelt** [BestImageViewer/geeqie#505]
I use Geeqie instead of Firefox file open dialogue, because Firefox uses GTK2 and doesn’t support large previews. Geeqie, on the other hand, allows to browse files quickly and has ‘copy path’ option in the drop down menu. 

But since I started to use Geeqie two or three years ago, I suffer from mishitting Delete, when I aim on Copy path. They are one under another. Provided, that I want to spend as few time as possible – I already lose time by switching to another window – I always click it in haste. 

I thought, that I will eventually stop mishitting Copy path, but again and again I had to go to my everstuffed trash bin folder and look for my files there. Later I changed my preferences and accidentally deleted files would go right to my XDG_DESKTOP_DIR. But since it is another kind of trash folder, I had to create ~/Desktop/GEEQIE_TRASH so the removed files would go there and could be easily found. But thinking about the problem, I got to understand, that those elements being too close and Delete action having red icon _inevitably_ would lead to mishitting Copy path in haste. So my suggestion is to surround Delete action with horizontal bars and give Copy path some recognisable icon. Like a large blue ellipsis, for example.

**Comment by caclark** [comment]
Fixed in commit 07b95e443e9 at geeqie.org.

The placement of Delete as the last-but-one item in a section seems illogical to me. Delete is now always the last item in a section, followed by a divider.

I am not sure a divider above the Delete item would be good - that would not be in line with standard practice.

There is no standard icon for copy path. It would also seem to be that the GTK3 programmers don't want icons on menus anyway. The gtk3 documentation states:  menu "actions" (or "verbs") should not have icons.
This also doesn't make sense to me - I can differentiate between coloured icons far easier than I can small text.
