### ISSUE TITLE
Release 1.4

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#530]
I set the release target for version 1.4 to 2017-12-01.

But as Colin did the most work in the last months, I think he has to say the last word about.

If there are any show stoppers, please attach them to the 1.4 milestone.

**Comment by caclark** [comment]
A new release is good news. Maybe getting a new release into the distributions may encourage others to help with the development.

The GTK3 problems are not going to be fixed in the short term (or any length of time).
There are a couple of issues listed that cause a crash, but in some way or other they are avoidable.

There is one segfault that is not yet listed - compile with GTK3, put a number (say 50 or more) images into a Collection, change the width of the Collection window and Geeqie will crash.
I have a patch for this, but even for me it is an outrageous hack. But no-one else has reported the problem, and the patch works for me, so I haven't bothered to try to solve it yet. I'm not sure what to do about this one.

I've run out of easy bugs to fix, and may not be involved too much over the next few weeks. I will be away all November and unfortunately (or maybe fortunately) the internet connection on the beach isn't so good.

December sounds ok to me

**Comment by PanderMusubi** [comment]
If you can please get a release out before January 2018, it might make it into Ubuntu 18.04.

**Comment by mowgli** [comment]
I'll try to release in the next days. It depend on the mailinglist now so the chances are high that I will get it out.

**Comment by tomaszg7** [comment]
I've been working on updating Polish translation, I'll try to finish it before then.

**Comment by tomaszg7** [comment]
Ok, here's the updated po file. I think it is more less accurate with the proviso that I don't use translated version at all. `poedit` shows an error in one entry, but I can't figure out why.

[pl.po.gz](https://github.com/BestImageViewer/geeqie/files/1590103/pl.po.gz)

**Comment by PanderMusubi** [comment]
Better to do that via https://www.transifex.com/iune/geeqie/ ?

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Am Do den 28. Dez 2017 um 14:56 schrieb Pander:
> Better to do that via https://www.transifex.com/iune/geeqie/ ?

I don't think so.

It is a good tool to translate but it has several disadvantages:
- - No offline edit
- - You need an extra account for it
- - Uses Javascript
- - Most important: Doesn't have klingon language file (tlh.po) :-)

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAlpFQ10ACgkQpnwKsYAZ
9qwSGAv9GFhfi4yCEBFMWSYjehR9MHLig/EvZeoh/KsMFO1wn5AWK6uW4tRN2U6c
ByobwDpgrrKchSVsH/nGXDTUmDGVzQ7ZbfsOubXa/MfN6ZhsE9UTk+XHeoI2SwSB
IjAZJXF9Ut5nzOM6/a0ZskOjK/124RQ6S2oVEtAt5KwaITSfWc9JaDjWBv8KfW0T
huRJJR0ox1DD+wp8Lt4lkZ85BvGm1j0rHwtrImqxEgshBY+8jvnMJfvSzs4PRFb9
tZSS0b0mnY19hLiY9x/+L4D2ExIgWWa934jxIAgoeiS0X5zzsiLcOeb4rPXz3dwE
vyzLVfLthxuqDVx8FR9FyRDuSQNobxyqGmrdYsFlgJz6fZ+q4fLe0kRlC1HCstFj
/B5zIu4p42N18k6JrFaXaUOqBh+s2axS7fJbs1V53CNKYq0C3k+8K2J4HVy6jNls
Xltpm714mMoYc/c+cg+g9wz861jt/NTf1ts3GS3s4QMqqzPfs9JOpp0B0oHCeys9
2PHTRnXD
=3utV
-----END PGP SIGNATURE-----

**Comment by PanderMusubi** [comment]
Request an account at Weblate? They give out free accounts to FOSS projects.

**Comment by tomaszg7** [comment]
Apparently my `intltool-update` didn't pick up all the text strings for some reason. I corrected that and also found several inconsistencies in grammar. Sorry for the mess.

[pl.po.gz](https://github.com/BestImageViewer/geeqie/files/1593375/pl.po.gz)

Also, before the release, you probably should see that patch as right now Geeqie might not compile with some versions of gcc/glibc/?: https://github.com/BestImageViewer/geeqie/issues/544#issuecomment-352810608

**Comment by mowgli** [comment]
Release v1.4 is out now.
