### ISSUE TITLE
gtk3 troubles

### ISSUE THREAD

**Issue by installgentoo** [BestImageViewer/geeqie#562]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
master
```

### OS / DISTRIBUTION
```
gentoo
```

### SUMMARY
in layout mode 3 
(1|2
 _|3)
if the file list is too thin(which is useful to have more pictures in the icon view) then gtk3 moves it and menu bar into the left side, moving the file tree off screen. with gtk2 it is moved to the right, which only hides help view plugins etc menu entries. this is obviously a preferred behaviour, as it allows you to still use file navigation.

file move popup is always squashed into the tiniest size possible in gtk3 and does not remeber its size or position. this is a really old problem with gtk3.

### STEPS TO REPRODUCE
-launch geeqie, select layout 3 and move file selecter tree border to the left
-move a file

btw, is gtk3 version experimental, or gtk2 abandoned? gtk3 seems to load thumbnails much faster than gtk2.

**Comment by caclark** [comment]
> if the file list is too thin(which is useful to have more pictures in the icon view) then gtk3 moves it and menu bar into the left side, moving the file tree off screen. with gtk2 it is moved to the right, which only hides help view plugins etc menu entries. this is obviously a preferred behaviour, as it allows you to still use file navigation.

My opinion is that the look-and-feel of the GTK2 version of Geeqie is better than the GTK3 version. Perhaps the only reason to use GTK3 is if you want to use the GPS map.

> file move popup is always squashed into the tiniest size possible in gtk3 and does not remeber its size or position. this is a really old problem with gtk3.

The latest version in the repository has an option to remember the size and position of dialog boxes. This option, which is off by default, is in Preferences/Windows

> btw, is gtk3 version experimental, or gtk2 abandoned?

Both versions are maintained. Any updates are made to both GTK2 and GTK3 versions.

> gtk3 seems to load thumbnails much faster than gtk2.

I made a quick look through the code, but I don't see any reference to GTK3 in the thumbnail code.

**Comment by installgentoo** [comment]
yes, the speedup seems to have be produced by me killing thumbnail cache.

thanks for the info!

**Comment by rockorequin** [comment]
> if the file list is too thin(which is useful to have more pictures in the icon view) then gtk3 moves it and menu bar into the left side, moving the file tree off screen. with gtk2 it is moved to the right, which only hides help view plugins etc menu entries. this is obviously a preferred behaviour, as it allows you to still use file navigation.

> 

Isn't this a bug that can be fixed? Other gtk3 applications - eg Nautilus - don't show this behaviour, so gtk3 must support the preferred behaviour. Is there perhaps an alignment setting for the file pane or parent pane that controls this?

> My opinion is that the look-and-feel of the GTK2 version of Geeqie is better than the GTK3 version. Perhaps the only reason to use GTK3 is if you want to use the GPS map.

> 
How can I select gtk2 as the interface? Is there a setting in preferences for this?

**Comment by caclark** [comment]
> Isn't this a bug that can be fixed? Other gtk3 applications - eg Nautilus - don't show this behaviour, 

For those with sufficient interest, you may run gtk-demo (for GTK2) and gtk3-demo (for GTK3), select the Paned Widgets example and compare the two.
I have made an internet search on this topic, but can find no reference to it, which I find surprising.
It may well be that experienced programmers know how to get round this problem, but unfortunately that isn't me. 

> How can I select gtk2 as the interface? Is there a setting in preferences for this?

You need to compile from sources - the option is:
./autogen.sh --disable-gtk3

If you are using a Debian-based system (Ubuntu etc), download and unzip the attached script and run it from the appropriate folder - if you want to easily switch between the two versions, this script will save a few keystrokes.

[geeqie-install-debian.sh.gz](https://github.com/BestImageViewer/geeqie/files/2235393/geeqie-install-debian.sh.gz)

**Comment by rockorequin** [comment]
@caclark: Thanks for the info!

For the discussion below, I have the default(?) geeqie setup of Tools+Files on the left and the image on the right (ie in a horizontal GtkPaned widget), ie the first layout in Edit / Configure This Window.

Comparing the gtk2 and gtk3 demos, if you have shrink=false for the left child window in the horizontal pane, you can only move the divider to the left until a certain point. If you have shrink=true, once you go past this certain point, gtk3 will scroll the contents of the left child window outside the paned widget, whereas gtk2 keeps the contents in the same place and obscures the right hand side of the text instead. This is exactly what we see geeqie doing in the gtk2 and gtk3 versions.

I can make geeqie do the same behaviour as nautilus (shrink = false) by changing the shrink flag to FALSE where the Tools widget is packed into the horizontal pane, ie by changing this in layout.c#layout_grid_setup():

```
	gtk_box_pack_start(GTK_BOX(lw->group_box), v, TRUE, TRUE, 0);

	if (!layout_location_first(priority_location))
		{
		gtk_paned_pack1(GTK_PANED(v), h, FALSE, TRUE);

```
to

```
	gtk_box_pack_start(GTK_BOX(lw->group_box), v, TRUE, TRUE, 0);

	if (!layout_location_first(priority_location))
		{
		gtk_paned_pack1(GTK_PANED(v), h, FALSE, FALSE);
```

... but of course this is not ideal because then the Tools+Files window can't be shrunk beyond a certain point. FYI, that point is currently determined by the width of the menu - if I don't show the menu, I can shrink Tools+Files quite a bit further. I know next-to-nothing about gtk3, so I don't know if it is possible to make the menu "wrap" when you shrink it. From what I can see of my other gtk3 windows, though, it never lets you hide parts of a menu like gtk2 does.

I experimented a bit with the shrunken Tools+Files (ie so it's scrolled off to the left) and found that when you click on the Files window scrollbar, it suddenly realises that it has scrolled way off to the left and allows you to scroll back, whereas the Tools/Dir window always thinks there is no need to scroll (ie it thinks the viewport and contents windows are the same width, even though manifestly they are not) - you need to turn the horizontal scrollbar to always on for this to occur. I experimented also with removing the shortcuts window from Tools and putting the Dir window directly into the Tools box, in case it was related to this.

**Comment by caclark** [comment]
I don't particularly care whether the pane scrolls left or -right - something is going to be hidden.
From my usage point of view, it would be better if there were a fourth, fixed, pane placed across the top of all four window layout options.
This pane would contain only the menu and the toolbar.
This would be an advantage for me, because the menus would never be hidden, and as I like to have quite a number of icons on the toolbar, they would all be visible.
The disadvantage is that some vertical space would be taken from the image (in layout 1) - not a problem for images in landscape mode, but obviously there would be in portrait mode.
So then we end up with the design requirement for a floating menu/toolbar that can be dragged either to the top or the side of the screen.
I feel the start of a headache :-(.

**Comment by rockorequin** [comment]
Personally I prefer the gtk2 behaviour because when the text scrolls off to the left you can't really read the directory names or filenames. But I like the way you're thinking - maybe we could have a header bar (ie replacing the titlebar) with the menu and/or toolbar in it?

**Comment by caclark** [comment]
The attached .diff file shows how it looks with the menu and toolbar at the top. This style is preferable for me, because the toolbar can extend right across the window.
Unfortunately the menu/toolbar ends up in the wrong place when the tools are floated. That's a pity - otherwise it would have been a simple fix.

[menu_toolbar_1.diff.gz](https://github.com/BestImageViewer/geeqie/files/2249102/menu_toolbar_1.diff.gz)

**Comment by rockorequin** [comment]
Yes, that's cool. I suppose you could move the menu and toolbar back into the file list if the file list is being floated?

I was actually thinking more about having the toolbar in a GtkHeaderBar, which would then replace the titlebar, freeing up more screen for the image. And I would put the menubar in as the application menu (https://developer.gnome.org/ApplicationMenu/). The geeqie code doesn't seem to be set up for a GtkApplication, so I wasn't able to mock this up properly. Instead, I've done a mock-up of how it might look if the application menu was in the header bar (I get gnome-tweaks to do this for my application menus, anyway):

[menu_toolbar_2.diff.gz](https://github.com/BestImageViewer/geeqie/files/2251963/menu_toolbar_2.diff.gz)

In the mockup, the menu now has a top-level item just called Menu that, when you click on it, shows the File, Go, Select etc menus. (I removed the Select and Plugin menus for this mock-up, but only because they get inserted at run-time at the top level next to Menu and I just want to show what it might look like rather than figure out how to move them.)

I don't gnome how non-gnome-shell desktop environments handle the header bar and application menu, though, so this might not work outside gnome-shell.

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

What I still see in gtk3 and what annoys me the most, is that it is not
possible anymore to scroll in image- or directory lists by mouse wheel.

I often have many thousand images in one dir. Not able to scroll with
mouse wheel is a pain in the a...

As debian decided to build geeqie with gtk3 enabled, I think I will
provide a gtk3 free build the next days.

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAltir94ACgkQpnwKsYAZ
9qw3LAv+JqLJxlWsB0eVNObUV9r8uS53VlsBinCZyjiZ8FlnGwWrAucvTR/E+KU9
ivd3XEiHXV17QWlDH8YTluCkZWu8t4edsd4NwhpcRqAbhsyxe7Um1qkrBkjDHnKw
A6Yy9ei8jZEuGsw9d4sfdVJWAs/1Qn0mDGDK3vD3Nro3r85ktg1DQxYF72RMI+M3
XaD+Q2JbK3zD93veI/SNWZcvb/niAD0cLHJ7w36VbRJ3zp7HCsJ5gVFQkRF+cEXF
RsUM8DcWSFE0Oa7aG5pEtp18ZaEA02Mjj0J0IqsYcbLmk0kNk4t6UxHHBpOKfWuR
g53VHutrELTu+lbnrKd/7sanYso+/yYiXWSfkLroBAEfyAIoXCyJh7oycLQF9mui
xATAYRpszm/4psrnEj8FcTXGGD2D4bvxluZYYdlcYGl74L5QriWe6G6c15wK+kcR
CZwoYaj4LBGQb1MqZTr2Jzp9TZq/IHWF1cEYXLPwFYG5k+FipEOME2X11/t654OS
iCNzGu5d
=1o52
-----END PGP SIGNATURE-----

**Comment by caclark** [comment]
> What I still see in gtk3 and what annoys me the most, is that it is not
possible anymore to scroll in image- or directory lists by mouse wheel.

Hello Klaus
Are you referring to the files pane? For me, mouse scroll works correctly in this pane in both GTK2 and GTK3.

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi Colin,

Am Do den  2. Aug 2018 um 11:32 schrieb Colin Clark:
> > What I still see in gtk3 and what annoys me the most, is that it is not
> possible anymore to scroll in image- or directory lists by mouse wheel.
> 
> Are you referring to the files pane?

yes.

> For me, mouse scroll works correctly in this pane in both GTK2 and GTK3.

That is strange. For me it only work with gtk2.

However, I did not check the current master with gtk3. I just keep it
compiled with gtk2.

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAlti7VMACgkQpnwKsYAZ
9qypIwv9FVyegMN3z7zCzwIhO90eSEh4WFGJG3heOSvFdeDJdxqG5owkOFeSHp1+
zMcNmsvVrhAFgJ1FtQTOX7u23HR44RXpuVMg1euzxSSW0A3qkyWZRcH7Oi4WDXRG
p1XKo/d2KrYoDZcu0nKqvzNdYIIQd1lMIPBLqxbffwVIa3c1xpnMmdEQjTv/NLQ0
GGS5HmjcYUkKgXEKrQcf0fU2NBIdYG88cz77LeA1ieuF4GE23o9v6vUoJYMwNKeg
T/F8C0Nka4buZ8j3Z++R9MFD0vDchuni1JxJU6fWrgk6iqtsvg+GzzmSmORM0x/F
fffUdq1HwJICQcepF1wHDf+1Mt/E6su6l56H+Q2Rn45atXIu60QF4+z9F7T+XuA4
zuRIO0w5ZUU5n3dU997/0Eg/jJIi3nWY/dJXci/BLxAdQL1CidnaeFQeiOpSBoNg
igNg1D2AUstN2gbeDs+SHrDhSeUR9IIGdmBMYzw7TBMVpLKE2EYabBJvQQkq/nIy
VkJi27BU
=Edu4
-----END PGP SIGNATURE-----

**Comment by caclark** [comment]
> I was actually thinking more about having the toolbar in a GtkHeaderBar, 

GtkHeaderBar is 3.10 or later. If this is considered a worthwhile addition, I would rather have something that would also benefit the hard-core GTK2 users.

>  I suppose you could move the menu and toolbar back into the file list if the file list is being floated?

I assume so, and that is the logical place. But it didn't look a trivial patch, so I did not want to bother until there were other comments about this.

In single-monitor use, I think that the advantage of having the menus and toolbar completely visible outweighs the disadvantage of smaller vertical space when viewing portrait-oriented images.
When using two monitors, one with the floated tools and the other with the image, this has to be the right way.

I'll get around to making the patch for the floated file list, and see how I feel about how that looks.

**Comment by caclark** [comment]
Attached is the .diff for a full-width menu and toolbar in normal and floated modes.
It works for both GTK2 and GTK3, and is conventional in appearance.
In my opinion the slight loss of height in normal mode is more than offset by the ease of use.
[menu_toolbar_3.diff.gz](https://github.com/BestImageViewer/geeqie/files/2263690/menu_toolbar_3.diff.gz)

**Comment by rockorequin** [comment]
My personal preference is to have more vertical room for the image. Is it possible to put the menu and toolbar in a box at the top so they are on the same level? Or incorporate the menu into the toolbar so it drops down from a button?

**Comment by caclark** [comment]
Commit bd11ce8 at geeqie.org moves the position of the menu/toolbar.

Note that the (perhaps excessive) padding around the icons in the toolbar does not come from Geeqie.
It is set by the theme you use - different themes have slightly different padding.

**Comment by rockorequin** [comment]
> By the way, there are shortcuts that will enable you to maximise the space for the image. There is a "hide toolbar" menu action - you can allocate a keystroke to that.

Is it possible to hide the menu as well as the toolbar, but without hiding the file list?

**Comment by caclark** [comment]
> Is it possible to hide the menu as well as the toolbar, but without hiding the file list?

Yes, I believe that can be done. But what about the status bar?
If this is implemented, you are mostly reliant on keystrokes to achieve anything.

**Comment by installgentoo** [comment]
original issue is largely fixed on master, there's an option in preferences
