### ISSUE TITLE
Move dialog starts out too small, doesn't remember last size

### ISSUE THREAD

**Issue by LdBarthel** [BestImageViewer/geeqie#587]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
"Geeqie 1.4"
"GTK3 3.22.26+161+g60750b3ffd" (current GTK3 package version)

### OS / DISTRIBUTION
Arch Linux, updated 2018-02-06

### SUMMARY
Hitting [CTRL]-M to move a file or files opens a dialog to select the destination directory. This dialog opens at a size too small to display the bookmarks, directory name, or subdirectories. After manually adjusting the dialog size, the conflict resolution dialog appears at a reasonable size. On the next invocation of the Move dialog, it appears at the original size.

### STEPS TO REPRODUCE
Attempt to move a file.
Resize the dialog and click through to complete the move.
Attempt to move another file. The dialog is tiny again.

**Comment by caclark** [comment]
I'm not able to reproduce this fault.
The operations copy, move and rename all use the same process for remembering the window size - if one works, they should all work.
After you have closed Geeqie, could you take a look at the contents of the file geeqierc.xml?
Towards the end you should see something like:

`        
<dialogs>
            <window title = "Move" role = "dlg_dest_folder" x = "727" y = "25" w = "594" h = "834" />
            <window title = "Move" role = "dlg_confirm" x = "508" y = "95" w = "695" h = "995" />
            <window title = "Copy" role = "dlg_dest_folder" x = "662" y = "277" w = "465" h = "766" />
            <window title = "Copy" role = "dlg_confirm" x = "565" y = "191" w = "612" h = "955" />
        </dialogs>
`
The parameters should of course change after you change the size of the windows.

**Comment by LdBarthel** [comment]
The <dialogs> entry did not exist in my geeqierc.xml.

However, this did point me in the direction of the fix. While searching for "dialog", I found `save_dialog_window_positions = "false"`

Changing this option fixed the problem.

By any chance, was this a new option where the behavior was broken out from the old "save_window_positions" option? I've been using geeqie since it was forked from GQView but never had this issue before. I'm wondering if the save_dialog_window_positions option defaulted to false because it didn't exist in my geeqierc.xml previously, instead of copying the value from save_window_positions.

**Comment by caclark** [comment]
The option was included because of the difference in behaviour when Geeqie is compiled with GTK2 or GTK.
When compiled with GTK2, the dialog sizes are acceptable.
When compiled with GTK3, the default sizes are too small to be useful.

I use dialog windows in a different way to the main windows, so I thought a separate option for the dialog windows was appropriate.
I set the default for the new option to false, so that GTK2 users would see no change in operation - maybe that was not the best choice.
If you prefer the GTK2 style of dialogs, that is still available to you with the
`autogen.sh --disable-gtk3` 
option.
