### ISSUE TITLE
Release 1.5?

### ISSUE THREAD

**Issue by Rio517** [BestImageViewer/geeqie#646]
I noticed that 1.4 stable is `157 commits behind master`. Would it make sense to make a 1.5 release before you get to 2.0? We're just passing the 1-year mark for the last stable release. 

P.S. I sincerely appreciate all the work you guys put into geegie. It makes it possible for me to work with RAW photos the way I like on Linux.

**Comment by caclark** [comment]
The print operation is usable but the conversion to the standard print op. is a bit half-baked at the moment.

I still plan to:
1) Change the image annotations to permit exif tags (as in Overlay Screen Display)
2) Interactive view of size and placement on the page (as in Gimp print preview)
3) Proof/contact print (as before in Geeqie)

I am not sure if anyone uses print - at one time I was thinking of just deleting it, but that seemed a bit drastic.

It might be worthwhile waiting for this to be completed - or maybe not....

**Comment by gusnan** [comment]
Soft freeze for the release of the next version of Debian is February 12th - It would be nice to have a release of Geeqie before that, so there's a chance to get that into the next Debian stable release.

And, as Rio517 above says - your work is appreciated!

**Comment by ahkok** [comment]
1.4 no longer compiles on newer compilers due to werror/deprecated warnings. 1.5 doesn't compile from tarball due to the version not being embedded in configure.ac, and our distro build system can't build from git (due to no network). So I can't currently package this without patching in our distro.

I'd really appreciate either a maintenance release or a new release! it would make every distro's life easier, not just mine.

**Comment by ArielRosenfeld** [comment]
It has been more then a year from the last release, making a new release would help distribution packagers as they always prefer official releases to using a snapshot.

having an official release also encourages new developers involvement as it creates an easier target for fixes as well as showing the project is still alive and active.

**Comment by alerque** [comment]
What @ArielRosenfeld said is stop on. Not having a release is making things hard for distributions (note how many people are having to [package snapshots downstream](https://repology.org/project/geeqie/versions)), is depriving most potential users of the best version of the software, and is a road block to community contribution. When the lifecycle is so long that people can't meaningful evaluate software based on what they install out of their distro's package manager the project it might be more meaningfully called a deathcycle. I like geeqie and have used it for many years, but even as somebody who can and does compile myself from git, this is a point of frustration for me to have to do on every system just to do basic stuff.

**Comment by alerque** [comment]
Thanks for the release! I see it's already [packaged](https://repology.org/project/geeqie/versions) for Arch Linux, Debian Unstable, and Ubuntu 19.10. That's awesome and I'm sure more will follow soon.

I highly recommend doing more smaller releases going forward. Cleanup whatever pain points there are in cutting a release so that it can be done more frequently to keep end users using the latest and greatest and developers interested.
