### ISSUE TITLE
Recursive slideshow" does not respect file sorting

### ISSUE THREAD

**Issue by vascotenner** [BestImageViewer/geeqie#664]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 1.4

```

```

```

### OS / DISTRIBUTION
Ubuntu

### SUMMARY
When using "Recursive slideshow" the file sorting (e.g. sort on exif date) is not respected: Files are shown in a different order.

### STEPS TO REPRODUCE

Create a folder with files that are sorted different on exif date than on file name, choose for sort on exif date and run slideshow recursively

**Comment by caclark** [comment]
If this were to be implemented, files would be sorted within each of the recursed folders.

[If you want files to be sorted within the complete set of data, I think the only way is to create a new collection, make an "add recursive" to it and then sort it.
The method of running a slideshow from a collection is not intuitive, because there is no right-click menu item - you have to drag a thumbnail onto the main image pane and run a slideshow from there.]

**Comment by vascotenner** [comment]
What I would expect that within every directory, the files are sorted according to the sort order and then displayed; e.g. like starting the slideshow from the different sub-directories subsequently. I do not expect to first collect all files and then order them.

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=56493b10ba396341971549ed1f3b11257103b105
