### ISSUE TITLE
Geeqie showing overwrite dialog on every single copy, even when not overwriting in destination directory

### ISSUE THREAD

**Issue by patrick-brian-mooney** [BestImageViewer/geeqie#673]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 1.4
```

### OS / DISTRIBUTION
Linux Mint 19.1

### SUMMARY
Geeqie (1.4, on x64 Linux Mint 19.1) is displaying an overwrite confirmation on every single copy instruction, whether or not it would result in overwriting a file in the destination directory. This is super-annoying: my "after dumping photos from my camera memory card" workflow involves going through folders sometimes holding thousands of pictures and copying many many individual photos and small groups. Adding another confirmation step adds up quickly in terms of extra mouse travel back and forth and back and forth and back and forth and back and forth and back and forth ...

I've skimmed through the preferences but can't find a way to turn this off. I've also tried deleting ~/.config/geeqie and ~/.cache/geeqie, then purging Geeqie and reinstalling it, but the behavior continues. Running Geeqie from a terminal doesn't show any relevant information.

### STEPS TO REPRODUCE
* Display an image in Geeqie;
* Right-click on image;
* Choose "Copy";
* Select a destination and click "OK";
* Overwrite dialog appears even when not overwriting.

A screencast demonstrating the problem: https://youtu.be/eoVKAMUopt0

**Comment by caclark** [comment]
Unfortunately there is no way to change this behaviour in v1.4.
(This problem has already been raised in https://www.freelists.org/archive/geeqie/, rather than here on github)
The problem has already been solved, but your only possibilities are to compile from sources or wait for the next release.
If you want to compile from sources, there is a script which will do that for you:
wget cclark.uk/geeqie-install-debian.sh

**Comment by patrick-brian-mooney** [comment]
Will do. Thank you so much for pointing me in the right direction.
