### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by Hofer-Julian** [BestImageViewer/geeqie#696]
Are you interested in providing geeqie as a Flatpak?

I could help you with that.

**Comment by paperdigits** [comment]
I have it mostly packaged already, I can upload the repo to github if you'd like to contribute.

**Comment by Hofer-Julian** [comment]
Whatever you prefer :)

**Comment by paperdigits** [comment]
You can find it here: https://github.com/pixlsus/flatpak-geeqie

I'd like to get the pixbuf loaders into geeqie, so we can view things like XCF and webp files.

**Comment by caclark** [comment]
There is already a WebP loader in the repo. at geeqie.org.

**Comment by caclark** [comment]
> so we can view things like XCF 

The source for an xcf loader is available. The Geeqie Help file points to where the compile and install instructions are. It is probably not too difficult to include the source of that loader into Geeqie. The problem is that it only handles xcf files up to v002. The latest version is 13, and it seems to me has much increased complexity. If you know of a loader that handles recent version of Gimp, that would be interesting to know. The xcf file spec. is here:
https://github.com/GNOME/gimp/blob/master/devel-docs/xcf.txt

**Comment by paperdigits** [comment]
@caclark is there any interest in bringing the Flatpak manifest into the main Geeqie source repo?

**Comment by caclark** [comment]
@paperdigits Packaging of Geeqie is not something I am involved with.The packaging and distribution is done by Klaus.  Actually I have no knowledge of modern methodologies and practices, so I have no idea of how popular/essential Flatpak and similar devices are. 
And trying to get an opinion out of the user-base is like trying to get blood out of  a stone.....

**Comment by paperdigits** [comment]
@mowgli do you have any interest in putting the Flatpak manifest in the source repo?

**Comment by Hofer-Julian** [comment]
This has been done for quite some time.
