### ISSUE TITLE
Use more descriptive Buttons in preference dialog

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#698]
Currently we have 5 Buttons in preference dialog:
* Help
* Save
* Apply
* Chancel
* Ok

It is not fully clear what the buttons does. I, for example, always press Apply -> Save -> Ok.

We should reduce the buttons and use a more clear description. (eg. Ok ahould apply too.)

**Comment by caclark** [comment]
The current actions are:

ok_button:
calls - config_window_apply();

apply_button:
calls - config_window_apply();
calls -layout_util_sync(lw);

save_button:
calls - config_window_apply();
calls - save_options(options);

cancel_button:
no actions

Therefore the save_button has the same action as the ok_button, because save_options() is always called when Geeqie exits.
The apply_button has the same action as the ok_button with the addition of layout_util_sync().

I suggest both the apply_button and the save_button are deleted, and layout_util_sync() added to the ok_button.

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=166d4ce5ce5698b15af0cc3f39f4ca4734ec8cce
