### ISSUE TITLE
Weird behavior when starting multiple instances of geeqie and closing windows.

### ISSUE THREAD

**Issue by Lovewyrm** [BestImageViewer/geeqie#707]
Geeqie 1.5, Slackware Linux 64 bit.
Ever since the update from 1.4 to 1.5 (at least I think that's how it is, I used geeqie 1.4 on mental autopilot for so long that I forgot, and the new toolbar threw me off immediately, for example, but that's not the point )
Windows seem to just pile up whenever a new instance is run, but when even one of those windows is closed, all windows are closed.
And when geeqie is started once more, all those previously closed windows come back.

This seems to be because the "exit the program when this window is closed" option is on by default.
I can't find this in the changelog, though, so I'm doubting my sanity somewhat here.

In any case, it's annoying, how do I change it back? If there was indeed a back to go back to.

I just want on demand geeqie windows in whichever workspace I am (using xmonad) , then closing that one specific window and having others stay open.
This used to be the case...I could swear that it is, but again, mental autopilot...that's how good geeqie is/was....

**Comment by Lovewyrm** [comment]
After deleting every occurence of `exit_on_close = "true" ` geeqierc file, all windows could be closed separately and new windows don't close everything else anymore by default, either.

**Comment by caclark** [comment]
Originally, each time Geeqie was called a completely new instance was initiated. 
This was changed because of #162, so that a "New Window" was started instead.
The options controlling window closing are buried in Edit/Configure This Window.
It would perhaps be more clear if closure was controlled by a menu option or a dialogue e.g. standard exit closes a single window, and a menu option to close all windows.
