### ISSUE TITLE
Feature Request: AV1 Image File Format support

### ISSUE THREAD

**Issue by ArielRosenfeld** [BestImageViewer/geeqie#776]
### ISSUE TYPE

* Feature Request

### GEEQIE VERSION

```
Geeqie 1.5.1
```

```
gtk2
```

### SUMMARY
Please add AVIF (AV1 Image File Format) support with [avif](https://github.com/AOMediaCodec/libavif)

**Comment by caclark** [comment]
libavif is not yet in the Debian repository.
If you find that it has been included, please notify via this issue.

**Comment by MPdaedalus** [comment]
+1,  want to convert my entire image bank to avif given that it blows everything else out of the water for quality/file size. Maybe you could embed the library in the binary instead of waiting for distro support. Fedora ain't gonna get libavif until october for me and debain will probably be even longer.

**Comment by caclark** [comment]
> Maybe you could embed the library in the binary

I don't think this is a good idea. Libavif is described as being work-in-progress (but I suppose Geeqie is too).

I could include the links to libavif in the image-loader part of Geeqie.
But that would require the user to compile from sources both libavif and the decoders.

I tried that, but very quickly gave up. It did not seem straightforward enough, to me.

If you could try to do that, and produce a simple step-by-step guide for installing the library and decoders, that would be a help.

**Comment by MPdaedalus** [comment]
Would love to help but my knowledge of compiling native programs is minimal. As a java developer there is something to be said for having everything in a single jar file with no dependencys, flatpak is a good alternative but the linux package ecosystem is the bane of my existence as we are all slaves to the distro maintainers who decide when and what library's are available.

**Comment by vstax** [comment]
> libavif is not yet in the Debian repository.

There is no need to use libavif and write extra code, supporting libheif (per #610 ) is enough as libheif  >= 1.7.0 adds AVIF support. Other applications, like ImageMagick decided to support AVIF through existing libheif code instead of adding extra libraries. In fact, I think AVIF will be automagically supported if libheif 1.7 is used and was built with AVIF support.

Both libavif and libheif wrap around libaom for actual AV1 support, so it's the same underlying implementation anyway

**Comment by caclark** [comment]
As stated above, AVIF is already supported.
