### ISSUE TITLE
Geeqie slow at startup, even when looking at just a single image

### ISSUE THREAD

**Issue by dkogan** [BestImageViewer/geeqie#814]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 1.5.1+git20200808-2a27c9ab
```

This is geeqie from Debian. Package version  1:1.5.1+git20200808-2a27c9ab-1

```
gtk3
```

### OS / DISTRIBUTION
Debian/sid

### SUMMARY
geeqie is very very slow at startup

### STEPS TO REPRODUCE
I'm in a directory that has slow I/O. In this case it is an sshfs remote mount, but that's a detail. This directory has a lot of files. Some images, some not.

I try to look at just a single image in this directory:

```
geeqie image.jpg
```

And this takes minutes to start up. The program just sits there in the shell without popping up the window. strace tells me that it's running stat() on every file in this directory. This is naturally slow, so it takes forever, but this is work that doesn't need to be done: I'm just looking at a single image, and geeqie knows which one. It should just show me the image.

I have pretty much everything turned off as much as possible. No thumbnails. Even if I "Hide file list" (C-h) it is still doing the work. I've looked around the preferences, and can't find an obvious switch.

Thanks!

**Comment by caclark** [comment]
The two most likely reasons are:
1. `Edit/Preferences/Behaviour/Save Marks On Exit` - make sure it is off.
2. Right-click on Files pane. Make sure `Show Star Rating` is off.

If 1. is the problem, there is a commit in the repo. at geeqie.org to fix that.
If 2. is the problem, maybe there will be a fix in a few days.... or weeks.

If neither, please let me know.

**Comment by dkogan** [comment]
Hi. Thank you for responding.

> 1. `Edit/Preferences/Behaviour/Save Marks On Exit` - make sure it is off.
> 2. Right-click on Files pane. Make sure `Show Star Rating` is off.

Both of these are off. Previously I had a slowdown issue when exiting,
and turning off "Save Marks On Exit" resolved that. This is a different
problem: the slowdown is on startup. And to be clear, this isn't a new
problem; the directory I'm looking at just has more stuff in it than
previous directories I'd be in.

Thanks

**Comment by caclark** [comment]
The marks file is looked for on start-up, every time - even if the `Save Marks` flag is off.
A quick check would be to rename `$HOME/.config/geeqie/marks` to a temp. name.
If that solves the problem, it will be necessary for you to use the latest commit from geeqie.org.

**Comment by dkogan** [comment]
> A quick check would be to rename `$HOME/.config/geeqie/marks` to a
> temp. name.

I just tried it, and it had no effect. geeqie still runs stat() on every
file in the directory. I can do some debugging. Would a backtrace for
the stat() be useful?

**Comment by caclark** [comment]
> Would a backtrace for the stat() be useful?

Not at the moment, thanks. I will do some thinking...

**Comment by caclark** [comment]
There is a commit at geeqie.org that addresses this problem:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=f8dcb10b89825eced654065c42ca61eaf6632220

It might solve the whole problem, or merely solve part of the problem.
If things are still slow, please let me know.

**Comment by dkogan** [comment]
Hi. I just built and ran the latest sources (including that patch), and
I see no difference: it's still really slow.

**Comment by caclark** [comment]
OK, thanks for trying that.
I would now be grateful of any debug data that you can supply (derived from the latest commit).

**Comment by dkogan** [comment]
OK. What kind of debug data would you like?

**Comment by dkogan** [comment]
I just got some backtraces, but I don't think I have the full DWARF
info. Suggestions to configure the geeqie build to compile with debug
information and no optimizations? Presumably there's some flag to
./configure or something? I'd like

  -g -O0 -fno-omit-frame-pointer

**Comment by caclark** [comment]
Perhaps:
`strace -e stat geeqie --debug=4  <somewhere>`
then control-c out as soon as something is displayed.
If the data contains any path info. you do do not want shown publicly, gitk shows my email address.
Thanks...

**Comment by caclark** [comment]
The problem lies deep in configuration/initialisation, where Geeqie always wants to display a folder.
Perhaps you could try the following workaround:
Apply the attached patch.
`src/geeqie --blank # or anywhere`
`src/geeqie --remote --view:<your_file>`
Or maybe just
`src/geeqie --remote --view:<your_file>`

If that works, please let me know, and I will apply the patch to the repo.. If it is ok, that will be a faster solution than me trying to unravel the initialisation sequence.

[814-1.diff.gz](https://github.com/BestImageViewer/geeqie/files/5317907/814-1.diff.gz)

**Comment by dkogan** [comment]
Hi.

1. I applied the patch.
2. `geeqie --blank` opens a new geeqie window with no image
3. `geeqie --remote --view:xxx.jpg` opens a NEW window with my
   image. Successfully. Trying this without the patch is really slow as
   before

Simply running `geeqie xxx.jpg` is still slow. Is that what we expect?

Thanks

**Comment by caclark** [comment]
> Simply running `geeqie xxx.jpg` is still slow. Is that what we expect?

Unfortunately that is so. 

The patch corrects a bug in the View In New Window code - the pre-patch code loads the entire folder instead of just the single file. This patch needs to go into the repo. at some time, anyway.

My suggested workaround forces Geeqie to open a blank folder/local folder  (which enables the initialisation process to complete), and then opens a single image in a new window (therefore without that entire folder being stat-ed).
I do not see any other way to quickly open a single file on a slow connection.
I do not see a way to open a single file in the main window, without Geeqie accessing the rest of that folder.

You should be able to open Geeqie with the single command:
`src/geeqie --remote --view:<file>`
  - in this case the folder displayed in the main window is determined by the default setting in `Edit/Configure This Window`

Unfortunately that is my only suggestion right now. I am not hopeful of separating the initialisation process so that a single image is displayed and then the contents of the folder loaded - even then, Geeqie would hang on a slow connection when accessing the rest of the folder.

I guess the solution would be to load the folder contents in the idle loop, but that would not be a quick fix.
