### ISSUE TITLE
The image rotation keys ([ and ]) affect the wrong image

### ISSUE THREAD

**Issue by dkogan** [BestImageViewer/geeqie#822]
* Bug Report

### GEEQIE VERSION
Latest build from git as of today:
```
Geeqie 1.5.1+git20201108-5dc8b463
```

```
gtk3
```

### OS / DISTRIBUTION
Debian/sid

### SUMMARY
[ and ] apparently don't work. Because they're affecting an image not currently displayed.

### STEPS TO REPRODUCE

1. `geeqie *.png`; the `*.png` is significant. This bug appears only when files are given on the commandline

2. Press [ or ]. Observe that the image is indeed rotated

3. Pgdown to move to the next image

4. Press [ or ]. Observe that the image is NOT rotated like it should be

5. Pgup to move back to the previous image. Observe that the [ or ] in step 4 actually affected this image instead of the one we were looking at.

**Comment by dkogan** [comment]
Hi. I just did a bisection, and found the breaking commit: fa4df0897c42bf74bfc280ee6bbf8c306ed8fd23

The message says that the changes the orientation keys to only affect the image that's "in focus". And now that I look at it, when you pgup/pgdown when looking at a specific set of images, the selected image in the file list on the left does NOT move, and that selected image is what [ and ] apply to now. Maybe pressing pgup/pgdown should update the file list also?

Maybe there's a fundamental confusing UI piece here. When you `geeqie img1.png img2.png img3.png`, the tool starts up showing just those images, and pressing pgup/pgdown cycles between only those images. But at the same time, the file list comes up, showing ALL the images in the directory, with `img1.png` selected, and pgup/pgdown does NOT affect the file list. Maybe pgup/pgdown should affect the file list, or maybe the file list should have some sort of indication that it's disconnected from the image being shown?

Thanks for working on this.

**Comment by caclark** [comment]
> Hi. I just did a bisection, and found the breaking commit
Thanks - but sorry, I should have already mentioned that I am looking at this problem. That commit was not entirely correct as a concept, and the problem anyway extends somewhat deeper into the start-up sequence.
(The computer I use for this died a few days ago, and I am waiting for some new parts to arrive - I live on a windswept rock in the middle of a windswept sea - parts availability here is limited and expensive, so I always have to order by post. Just takes a while.)

**Comment by dkogan** [comment]
No worries, and again, I really appreciate you taking care of this project. Let me know if any more debugging is helpful.

**Comment by tomaszg7** [comment]
I tried reproducing your problem with file list focus not following main window (as I saw similar issue before but the other way round https://github.com/BestImageViewer/geeqie/issues/769) and I noticed some inconsistency in Geeqie's behaviour.

When I use `geeqie img1.png img2.png img3.png` I indeed see what you described. However when I specify only one filename, Geeqie does not restrict to that file while using PgUp/Dn (although it is focused when Geeqie starts). It may lead to unforeseen behaviour when using commands like `geeqie *png`. You would expect restricted cycling, however when it happens that there is only one png file, you don't get it.

**Comment by caclark** [comment]
If `geeqie xyz.jpg` is executed, the initial folder setting in `Configure this window` is ignored, and the files pane shows the folder that contains `xyz.jpg` with `xyz.jpg` highlighted.

If `geeqie –list *.jpg` is executed, a temporary collection window is opened. The initial folder setting is ignored and the folder containing `*.jpg` is displayed. The first image in the `*jpg` sequence is highlighted in the files pane, but the files pane remains static. `Back/forward` will cycle through the files in the collection window, with the current image being highlighted in the collection window.

If `geeqie *.jpg` is executed, a temporary collection is created as above, but the collection window is not displayed. `Back/forward` cycles through the command line (temporary collection) files, as above.

If a collection window is opened from the command line, the initial folder setting is honoured, the first image in the folder is highlighted but the files pane remains static. The image pane is set to the first image in the collection. `Back/forward` cycles though the collections window and highlights the image currently selected.

The separation of files pane and adjoining image pane, and the collection window, I find a bit confusing. Since I started using Geeqie I have wanted the collection files to be displayed in the files pane with the collection treated as a virtual folder. But this is not a trivial change.

Which image is being accessed by the rotate command is a part of the confusion about where the focus currently is – and grouping is also part of the problem because the files filter in initialised too late in the start sequence.

**Comment by caclark** [comment]
>  Since I started using Geeqie I have wanted the collection files to be displayed in the files pane with the collection treated as a virtual folder.

Maybe a possibility is to create a temp folder in `/tmp/geeqie/<collection-name>/` and symlink the collections files there. Presumably I thought of that before, and discarded it because of problems - or maybe not. The collection window has the possibility of manual/random arrangements - but maybe that functionality could be included somehow in the files pane.
