### ISSUE TITLE
--remote --File=IMAGE fails: not displaying image, not using running instance, not forking

### ISSUE THREAD

**Issue by mviereck** [BestImageViewer/geeqie#871]
Bug report:
I am using geeqie very often in some scripts with this syntax:
```
geeqie --remote --File:IMAGE
```
After a recent update on Debian 10/bullseye/testing (geeqie version 1.6) this does not work anymore.

Expected behaviour (as has been before):
 - `geeqie -t -r --File:IMAGE` sends the file name to an already running instance of geeqie (or starts the first one).
 - The image is shown in the remote instance of geeqie.
 - The command `geeqie -t -r --File:IMAGE` exits and my script can continue.

Actual behaviour:
 - Always a new instance of geeqie is started.
 - Some random image is shown, not the one I've send.
 - The command does not exit but blocks the terminal.

I am not sure if this issue is specific to the debian testing package. So far I did not build geeqie myself; some first attempts failed. It would be nice if you could just check if you can reproduce the issue already. If you cannot reproduce, I'll investigate further.

**Comment by caclark** [comment]
> If you cannot reproduce, I'll investigate further

Thanks, but I know where the fault is. It will be fixed in a couple of days.

> So far I did not build geeqie myself; some first attempts failed

If you are using Debian, there is a script to install from sources. If you want to use the updated code immediately it is in the repo.,  you might find it easier to use the script.

`wget https://raw.githubusercontent.com/BestImageViewer/geeqie/master/web/geeqie-install-debian.sh`

**Comment by mviereck** [comment]
> Thanks, but I know where the fault is. It will be fixed in a couple of days.

Great!
Will the fix get into Debian testing, too?

> If you are using Debian, there is a script to install from sources. 

I failed using this script in a Dockerfile.
Looking at it: 
Likely it failed because it uses `zentity` for some user interaction. This is not possible within a docker image build process; there a script must run non-interactive.

**Comment by gusnan** [comment]
> Great!
> Will the fix get into Debian testing, too?

Is there a bug for the problem in the Debian bug tracking system?
Debian is in "soft freeze" now, for the release of the next Debian version.
If you want a bug in geeqie that is packaged in Debian to be fixed, report it as a bug on the package in the Debian bug tracking system. The chances to get a new version into testing now smaller during the freeze, and grows smaller the longer into the freeze we are. For a bug to be fixed in Debian it simplifies things MASSIVELY to have them reported in the Debian bug tracking system, with a proper severity level. (The higher the severity level the higher the chance to get a fix into testing, but with this said, don't submit bugs with a higher severity level than the problem deserves),

**Comment by mviereck** [comment]
> Is there a bug for the problem in the Debian bug tracking system?

I've reported the bug at debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=983546
Thank you for pointing me onto this.

**Comment by gusnan** [comment]
@mviereck Thanks! That helps.

**Comment by caclark** [comment]
Fixed in commit:
https://github.com/BestImageViewer/geeqie/commit/100bd6ae6d964b9072777440ab98fb3187e90d2e

**Comment by mviereck** [comment]
> Fixed in commit:
100bd6a

Great, thank you!

**Comment by gusnan** [comment]
@mviereck And the fix has been uploaded to Debian unstable, and with an unblock request to get it into testing:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=983628

So now it is up to the Debian release team if we get into testing. (I believe it shouldn't be a problem).

**Comment by mviereck** [comment]
>  the fix has been uploaded to Debian unstable, and with an unblock request to get it into testing:

Thank you!
Yet I've build `Geeqie 1.6+git20210227-100bd6ae GTK3` and can confirm that the bug is fixed in all aspects.
